#!/usr/bin/env python3
"""Give the tool pages (mes.fm/emoji, /latex, /timezone, /symbols, /speedreader, /timer, /youtube-thumbnail,
/stats) the same floating header bar and A- / A+ / moon display controls as the hub pages and mes.fm/math.

Per page this script (idempotent; re-running refreshes the generated dark block):

  1. FLOATING BAR -- the slim fixed bar (small tool logo + title + nav links + pinned hamburger) that slides in
     once the real header scrolls away. CSS / markup / JS are reused from add_compact_nav_bar.py (imported), with
     the hub blue swapped for the tool's own shell colour (its `.info-bar,.color-box,.navbar,.footer` colour).
  2. CONTROLS -- `<script src="/main_js/display-controls.js" defer>` (A-/A+ text size, moon/sun dark mode, shared
     `articleFontScale` / `theme` localStorage keys with mes.fm/math) and `<div id="main-content" data-tool
     data-text-scale>`, which opts the tool area into text scaling and the tool-page dark treatment there.
  3. DARK MODE FOR THE WIDGET -- each tool has its own light widget CSS (white tiles, #f7f8fa inputs, dark-grey
     text ...), so a block of `body.dark-mode ...` overrides is *derived* from that page's own tool <style>
     between /* TOOL-DARK:START */ and /* TOOL-DARK:END */: every rule that sets a colour gets a mapped
     counterpart (neutrals are lightness-inverted, pastel tints darkened, saturated accents lightened just enough
     to read on dark, near-white text kept for text sitting on accent buttons). Edit the tool's CSS, re-run this.

**Dry-runs by default; `--apply` writes.**
"""
import colorsys
import re
import sys
from pathlib import Path

import add_compact_nav_bar as cnb

ROOT = Path(__file__).resolve().parent
SITE = ROOT / "mes.fm"
APPLY = "--apply" in sys.argv

TOOLS = [  # (directory, compact-bar title)
    ("emoji", "Emoji Copier"),
    ("latex", "LaTeX Render"),
    ("timezone", "Timezone Converter"),
    ("symbols", "Symbol Copier"),
    ("speedreader", "Speed Reader"),
    ("timer", "Timer"),
    ("youtube-thumbnail", "YouTube Thumbnail"),
    ("stats", "Stats"),
]

START, END = "/* TOOL-DARK:START -- generated by add_tool_page_controls.py, do not edit */", "/* TOOL-DARK:END */"
DC_TAG = '<script src="/main_js/display-controls.js?v=1.6" defer></script>'


# ------------------------------------------------------------------ colour mapping
def parse_color(tok):
    tok = tok.strip().lower()
    if tok == "white":
        return (255, 255, 255, 1.0)
    if tok == "black":
        return (0, 0, 0, 1.0)
    if tok.startswith("#"):
        h = tok[1:]
        if len(h) in (3, 4):
            h = "".join(c * 2 for c in h)
        r, g, b = int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16)
        return (r, g, b, int(h[6:8], 16) / 255 if len(h) == 8 else 1.0)
    m = re.match(r"rgba?\(([^)]*)\)", tok)
    if m:
        p = [x.strip() for x in re.split(r"[,/\s]+", m.group(1).strip()) if x.strip()]
        r, g, b = (float(x) for x in p[:3])
        a = float(p[3].rstrip("%")) / (100 if p[3].endswith("%") else 1) if len(p) > 3 else 1.0
        return (r, g, b, a)
    return None


def fmt(r, g, b, a):
    r, g, b = (max(0, min(255, round(v))) for v in (r, g, b))
    return "#%02x%02x%02x" % (r, g, b) if a >= 0.999 else "rgba(%d,%d,%d,%.2f)" % (r, g, b, a)


def map_color(tok, kind):
    """kind: text | bg | border | var"""
    c = parse_color(tok)
    if c is None:
        return tok
    r, g, b, a = c
    h, l, s = colorsys.rgb_to_hls(r / 255, g / 255, b / 255)
    neutral = s < 0.30
    if kind == "text":
        if l > 0.9:
            return tok                       # near-white text sits on an accent/dark surface: keep
        if neutral:
            l2 = min(0.95, max(0.62, 1 - l))
        else:
            l2 = max(l, 0.68)                # saturated accent text: lighten enough to read on dark
        s2 = s if not neutral else s * 0.5
    elif kind == "bg":
        if l > 0.72:                         # white / pastel tint -> dark surface
            l2 = min(0.24, max(0.10, 1 - l + 0.06))
            s2 = s * 0.45
        elif neutral:
            l2 = min(0.32, 1 - l) if l < 0.6 else 0.16
            s2 = s
        else:
            return tok                       # saturated mid/dark background (accent buttons, badges): keep
    elif kind == "border":
        if neutral:
            l2 = min(0.42, max(0.20, 1 - l + 0.06)) if l > 0.5 else max(l, 0.3)
            s2 = s
        else:
            l2 = max(l, 0.5) if l < 0.5 else min(0.4, 1 - l + 0.1)
            s2 = s
    else:  # var: custom property used as accent both for text and fills
        if neutral:
            return tok
        l2, s2 = max(l, 0.52), s
    r2, g2, b2 = colorsys.hls_to_rgb(h, l2, s2)
    return fmt(r2 * 255, g2 * 255, b2 * 255, a)


COLOR_RE = re.compile(r"#[0-9a-fA-F]{8}\b|#[0-9a-fA-F]{6}\b|#[0-9a-fA-F]{3}\b|rgba?\([^)]*\)|\bwhite\b|\bblack\b")


def prop_kind(prop):
    p = prop.strip().lower()
    if p.startswith("--"):
        return "var"
    if p in ("color", "fill"):
        return "text"
    if p in ("background", "background-color", "background-image"):
        return "bg"
    if p in ("stroke",) or p.startswith("border") or p in ("outline", "outline-color"):
        return "border"
    return None


# ------------------------------------------------------------------ css parsing
def strip_comments(css):
    return re.sub(r"/\*.*?\*/", "", css, flags=re.S)


def blocks(css):
    """Yield (selector, body) for every top-level rule; descend into @media (skipping @media print)."""
    i, n = 0, len(css)
    while i < n:
        j = css.find("{", i)
        if j < 0:
            break
        sel = css[i:j].strip()
        depth, k = 1, j + 1
        while k < n and depth:
            depth += {"{": 1, "}": -1}.get(css[k], 0)
            k += 1
        body = css[j + 1:k - 1]
        if sel.startswith("@media"):
            if "print" not in sel:
                yield from blocks(body)
        elif not sel.startswith("@"):
            yield sel, body
        i = k


def derive_dark(tool_css):
    out, seen = [], set()
    for sel, body in blocks(strip_comments(tool_css)):
        decls = []
        for d in re.split(r";(?![^(]*\))", body):
            if ":" not in d:
                continue
            prop, val = d.split(":", 1)
            kind = prop_kind(prop)
            if not kind or "url(" in val or "var(" in val and kind != "var" and not COLOR_RE.search(val):
                continue
            new = COLOR_RE.sub(lambda m: map_color(m.group(0), kind), val)
            if new != val:
                decls.append("%s:%s" % (prop.strip(), new.strip()))
        if not decls:
            continue
        parts = [s.strip() for s in re.split(r",(?![^(]*\))", sel) if s.strip()]
        parts = [s for s in parts if not re.match(r"^(a|body|html|\*)(?![\w-])", s) and not s.startswith(".hide")]
        if not parts:
            continue
        rule = "%s{%s}" % (",".join("body.dark-mode " + s for s in parts), ";".join(decls))
        if rule not in seen:
            seen.add(rule)
            out.append(rule)
    return out


GENERIC = (
    "body.dark-mode .page-content :where(div,span,p,li,ul,ol,h1,h2,h3,h4,h5,h6,td,th,label,summary,small,strong,b,em,i,code,pre,"
    "legend,figcaption,button,input,select,textarea){color:#d8d8d8}\n\t"
    "body.dark-mode .page-content code{background-color:#33363d;color:#f0a8bd}\n\t"   # bootstrap's pink-on-pink <code> chip
    "body.dark-mode .page-content .btn-default{background-color:#2e2e2e;background-image:none;color:#ddd;border-color:#555}"   # bootstrap default buttons (speedreader)
)


# ------------------------------------------------------------------ page patching
def accent_of(text):
    m = re.search(r"\.info-bar,\.color-box,\.navbar,\.footer\s*\{background-color:(#[0-9a-fA-F]{6});", text)
    return m.group(1) if m else None


def tool_style_span(text):
    """(start, end) of the tool-specific <style> body: the one after '</style>\\t<style>' and before fb:app_id."""
    m = re.search(r"</style>\s*<style>", text)
    if not m:
        return None
    s = m.end()
    e = text.index("</style>", s)
    return s, e


def compact_css(accent):
    css = cnb.CSS_TEMPLATE.replace("#277bb6", accent)
    r, g, b = (int(accent[i:i + 2], 16) for i in (1, 3, 5))
    css = css.replace("rgba(39,123,182,", "rgba(%d,%d,%d," % (r, g, b))
    return css.replace("this page has no #header-controls div, so there's\n   less to reserve room for.",
                       "display-controls.js pins the A-/A+/moon buttons into its right end.")


def patch(text, dirname, title):
    notes = []
    accent = accent_of(text)
    if not accent:
        return None, ["no shell accent colour found"]
    span = tool_style_span(text)
    if not span:
        return None, ["tool <style> not found"]
    logo = re.search(r'data-src="(/[^"]*/logo\.png[^"]*)"', text)
    logo = logo.group(1) if logo else "https://mes.fm/img/logo-mark.png"

    # -- 3. generated dark block (strip any previous copy first so the derivation sees only hand-written CSS)
    text = re.sub(r"\n\t" + re.escape(START) + r".*?" + re.escape(END) + r"\n", "", text, flags=re.S)
    s, e = tool_style_span(text)
    dark = derive_dark(text[s:e].replace(compact_css(accent), ""))
    block = "\n\t%s\n\t%s\n\t%s\n\t%s\n" % (START, GENERIC, "\n\t".join(dark), END)
    text = text[:e] + block + text[e:]
    notes.append("dark: %d rules" % len(dark))

    # -- 1. floating bar
    if 'id="compact-nav"' not in text:
        css = compact_css(accent)
        m = cnb.CSS_ANCHOR_RE.search(text)
        if not m:
            return None, ["compact-nav CSS anchor not found"]
        text = text[:m.start()] + css + text[m.start():]
        if text.count(cnb.HTML_ANCHOR) != 1 or text.count(cnb.JS_ANCHOR) != 1:
            return None, ["compact-nav HTML/JS anchor not found"]
        html = cnb.build_html(title, "/" + dirname).replace("https://mes.fm/img/logo-mark.png", logo)
        html = re.sub(r'    <li><a href="/" tabindex="-1"><b>MES.fm</b></a></li>',
                      '    <li><a href="/" tabindex="-1"><b>MES.fm</b></a></li>', html)
        text = text.replace(cnb.HTML_ANCHOR, html + cnb.HTML_ANCHOR, 1)
        text = text.replace(cnb.JS_ANCHOR, cnb.JS_ANCHOR + cnb.JS_BLOCK, 1)
        notes.append("floating bar")

    # -- 2. controls
    if DC_TAG not in text:
        if "display-controls.js" in text.split("</style>")[-1]:
            text = re.sub(r'<script src="/main_js/display-controls\.js[^"]*" defer></script>', DC_TAG, text, count=1)
        else:
            text = text.replace(cnb.JS_BLOCK, cnb.JS_BLOCK + DC_TAG, 1)
        notes.append("controls script")
    if 'id="main-content" data-tool' not in text:
        if text.count('<div id="main-content">') != 1:
            return None, ["#main-content not unique"]
        text = text.replace('<div id="main-content">', '<div id="main-content" data-tool data-text-scale>', 1)
        notes.append("data-tool")
    return text, notes


def main():
    changed = 0
    for d, title in TOOLS:
        p = SITE / d / "index.html"
        old = p.read_text(encoding="utf-8")
        new, notes = patch(old, d, title)
        if new is None:
            print("%-18s SKIPPED: %s" % (d, "; ".join(notes)))
            continue
        print("%-18s %s%s" % (d, "; ".join(notes), "" if new != old else "  (no change)"))
        if new != old:
            changed += 1
            if APPLY:
                p.write_text(new, encoding="utf-8")
    print("%d pages %s" % (changed, "written" if APPLY else "would change (dry run -- pass --apply)"))


if __name__ == "__main__":
    main()
