#!/usr/bin/env python3
"""Add a "Conspiracy" info-bar link to the 9/11-family hand-built mirror pages.

The mes.fm/911 family's horizontal info-bar reads "9/11 Truth | Calculators | Tools | ...".
Conspiracy (mes.fm/conspiracy) is more relevant to these pages than the generic
Calculators/Tools links, so a "Conspiracy" item is inserted right after "9/11 Truth" and
before "Calculators" -- matching the request to put it "after 9/11 Truth, before calculators".

Only touches the top info-bar (#info-bar), not the hamburger dropdown nav (#navbar), and
only the hand-built static pages (cloned from hive_mirror_template.html by
convert_mirror_pages.py) -- the 7 pages generated by mes.fm/911/build.mjs are handled by
editing that file's own template and rebuilding (npm run build), not by this script.

Idempotent (skips a file that already links Conspiracy in its info-bar).
Dry-runs by default -- pass --apply to write.
"""
import argparse
import glob
import os
import re

ROOT = os.path.dirname(os.path.abspath(__file__))
SITE = os.path.join(ROOT, "mes.fm")

ANCHOR_RE = re.compile(
    r'(<li class="info-bar__item"><a target="_self" class="info-bar__item__text" href="/911">9/11 Truth</a></li>\n)'
    r'(\s*)(<li class="info-bar__item"><a class="info-bar__item__text" href="/calculators">Calculators</a></li>)'
)
NEW_ITEM = '<li class="info-bar__item"><a class="info-bar__item__text" href="/conspiracy">Conspiracy</a></li>\n'


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--apply", action="store_true", help="write changes (default: dry run)")
    ap.add_argument("-v", "--verbose", action="store_true", help="list every page")
    args = ap.parse_args()

    total = changed = 0
    skipped = []
    for path in sorted(glob.glob(os.path.join(SITE, "*", "index.html"))):
        with open(path, "r", encoding="utf-8") as f:
            old = f.read()
        if 'href="/911">9/11 Truth</a></li>' not in old:
            continue
        total += 1
        if 'href="/conspiracy">Conspiracy</a></li>' in old:
            continue  # already has it
        new, n = ANCHOR_RE.subn(lambda m: m.group(1) + m.group(2) + NEW_ITEM + m.group(2) + m.group(3), old, count=1)
        if n == 0:
            skipped.append(os.path.relpath(path, ROOT))
            continue
        if new != old:
            changed += 1
            if args.verbose:
                print("  %s %s" % ("write" if args.apply else "would write", os.path.relpath(path, ROOT)))
            if args.apply:
                with open(path, "w", encoding="utf-8", newline="") as f:
                    f.write(new)
    print("%s: %d of %d matching pages %s" % ("APPLIED" if args.apply else "DRY RUN", changed, total,
                                               "changed" if args.apply else "would change"))
    if skipped:
        print("Skipped (no anchor match): %d" % len(skipped))
        for s in skipped:
            print("  " + s)
    if not args.apply:
        print("(dry run -- pass --apply to write)")


if __name__ == "__main__":
    main()
