#!/usr/bin/env python3
"""Phone-width fixes for the math-hub page header and its floating bar.

Two problems, reported from a phone (2026-09-25):

1. Squished title. The A-/A+/moon controls and the hamburger shared the header's
   top row with the logo and title, so the title/tagline got only what was left
   (~130px on a 411px phone with large system text): "MES / Math / Tutorials".
   At <=480px the controls now drop to their own row under the header, right-
   aligned beneath the hamburger, and the title gets the whole width. The row is
   `position:absolute; bottom:0` inside a header that reserves the space with
   padding-bottom, so nothing reflows when the bar sticks and the controls fly
   up into it.

2. Cut-off controls in the floating bar on mes.fm/math (and its five sibling
   hubs): the <=768px header rule centres #header-controls with
   `top:50%; transform:translateY(-50%)`; once stuck, `top:13px` replaced the
   top but the transform stayed, lifting the A-/A+/moon buttons ~14px so their
   top half was clipped by the top of the screen. Stuck state now resets the
   transform.

3. Sideways scroll on phones: a long unbroken URL in a mirrored article (Problems Plus 5's
   grok.com share link) is wider than the screen and can't wrap, so the page scrolled
   left/right. `article { overflow-wrap: anywhere }` lets such links break.

Two families of pages carry the header (see the anchors below):
  * `#header-controls` (mes.fm/math + math-qa, sequences-series, vectors,
    vector-functions, spherical-harmonics; generated by math/build.mjs), and
  * `.header-controls` (Problems Plus, cubic formula, Q/A pages, Hive-mirror
    pages, ...; ~175 pages plus their generators/templates).

Patched: every *.html / *.mjs / *.py under the repo that carries one of those
480px compact-nav blocks (generated pages AND the templates that emit them, so
a rebuild keeps the fix). Idempotent (MOBILE-HEADER-CONTROLS-ROW marker);
dry-runs by default, --apply writes.
"""
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SKIP_DIRS = {"node_modules", ".git", "worktrees", "percentagecalculator-app", ".claude"}
SELF = Path(__file__).name
MARK = "MOBILE-HEADER-CONTROLS-ROW"

# The 480px block every page carries (indent captured so generators' indentation is kept).
ANCHOR_CLASS = re.compile(
    r"(?P<i>[ \t]*)@media \(max-width: 480px\) \{\n"
    r"[ \t]*#compact-nav \{ padding-right: 160px; gap: 8px; \}\n"
    r"[ \t]*body\.is-stuck \.header-controls \{ right: 56px; \}\n"
    r"[ \t]*\}\n"
)
ANCHOR_ID = re.compile(
    r"(?P<i>[ \t]*)@media \(max-width: 480px\) \{\n"
    r"[ \t]*#compact-nav \{ padding-right: 160px; gap: 8px; \}\n"
    r"[ \t]*body\.is-stuck #header-controls \{ right: 56px; \}\n"
    r"[ \t]*\}\n"
)

BLOCK_CLASS = """\
/* MOBILE-HEADER-CONTROLS-ROW: on phones the A-/A+/moon controls sit on their own row
   under the brand (absolute, so sticking into the floating bar doesn't reflow), which
   leaves the title/tagline the full width instead of a ~130px sliver. */
/* Also: a long unbroken URL in the article text (e.g. a 70-char grok.com share link on
   Problems Plus 5) made the whole page wider than a phone, so it scrolled sideways. */
article { overflow-wrap: anywhere; }
@media (max-width: 480px) {
  .top-bar { padding-bottom: 44px; }
  .header-controls { position: absolute; right: 8px; bottom: 0; margin-left: 0; }
  body.is-stuck .header-controls { bottom: auto; }
}
"""

BLOCK_ID = """\
/* MOBILE-HEADER-CONTROLS-ROW: (1) stuck controls drop the 768px rule's translateY(-50%),
   which was lifting them ~14px so the top of the A-/A+/moon buttons was clipped; (2) on
   phones the controls take their own row under the brand (absolute, so sticking into the
   floating bar doesn't reflow) and the title/tagline get the full width. */
body.is-stuck #header-controls { transform: none; bottom: auto; }
@media (max-width: 480px) {
  .header { padding-right: 56px !important; padding-bottom: 44px !important; }
  #header-controls { top: auto; bottom: 0; right: 8px; transform: none; }
  body.is-stuck #header-controls { top: 13px; bottom: auto; }
}
"""


def indent(block: str, pad: str) -> str:
    return "".join((pad + ln if ln.strip() else ln) for ln in block.splitlines(True))


def patch(text: str):
    if MARK in text:
        return text, 0
    n = 0
    for anchor, block in ((ANCHOR_CLASS, BLOCK_CLASS), (ANCHOR_ID, BLOCK_ID)):
        def repl(m, block=block):
            nonlocal n
            n += 1
            return m.group(0) + indent(block, m.group("i"))
        text = anchor.sub(repl, text)
    return text, n


def main():
    apply = "--apply" in sys.argv
    changed = []
    for ext in ("*.html", "*.mjs", "*.py"):
        for p in ROOT.rglob(ext):
            if SKIP_DIRS & set(p.relative_to(ROOT).parts) or p.name == SELF:
                continue
            try:
                text = p.read_text(encoding="utf-8")
            except (UnicodeDecodeError, OSError):
                continue
            if "compact-nav { padding-right: 160px; gap: 8px; }" not in text:
                continue
            new, n = patch(text)
            if n:
                changed.append(p.relative_to(ROOT))
                if apply:
                    p.write_text(new, encoding="utf-8")
    for p in changed:
        print(("patched  " if apply else "would patch  ") + str(p))
    print(f"\n{len(changed)} file(s) {'patched' if apply else 'would change (dry run; pass --apply)'}")


if __name__ == "__main__":
    main()
