#!/usr/bin/env python3
"""
Lengthen too-short <meta name="description"> text across the deployed mes.fm/ tree.

Bing Webmaster Tools ("Recommendations" -> "Meta descriptions on many of your pages are too short") flagged ~281
pages. The offenders are mostly the templated calculator-site pages (memes, quotes, dream homes, articles, ...) whose
descriptions were 15-100 characters, plus a few dozen one-off pages, and a handful of pages with no description at all.

For every page under mes.fm/ whose description is missing or shorter than MIN_LEN (120 chars; Bing recommends
150-160), this script builds a longer one:

  * lead  - the page's own description when it says something real, else built from the page title + its category
            ("Tepoztlan Lounge ... - a dream home feature for mortgage shoppers.")
  * tail  - a site-specific sentence (free BMI calculator, ...) in several lengths; the longest that keeps the total
            under MAX_LEN is used.
  * pages with hand-written copy (calculator homepages, top-level pages, puzzle hubs, ...) come from HAND_WRITTEN.

og:description / twitter:description are kept in sync when they were identical to the old description, and a missing
<meta name="description"> is inserted. Idempotent: a description already >= MIN_LEN is left alone, so re-running is a
no-op. Dry-runs by default; pass --apply to write. Skips HTTrack `_http_`/`_https_` captures, templates, "Page Not
Found" stubs, and pages generated by a build.mjs / build_math_qa_mirrors.py (fix those in their generators).
"""
import glob
import html
import os
import re
import sys

ROOT = os.path.join(os.path.dirname(os.path.abspath(__file__)), "mes.fm")
MIN_LEN = 120
MAX_LEN = 168

META_RE = re.compile(r'<meta\s+[^>]*?name=["\']description["\'][^>]*>', re.I)
CONTENT_RE = re.compile(r'content=(["\'])(.*?)\1', re.I | re.S)
TITLE_RE = re.compile(r"<title>(.*?)</title>", re.I | re.S)
OG_TITLE_RE = re.compile(r'<meta\s+property=["\']og:title["\']\s+content=(["\'])(.*?)\1', re.I | re.S)
BOILER_RE = re.compile(r"\s[–-]\s.+\s[–-]\s")  # "Title - Category - Site."

# Directories that are generated (edit the generator, not the output) -- see CLAUDE.md.
GENERATED = {
    "911", "911-alchemy", "conspiracy", "cubic-formula", "djw", "ferrocell-specular-reflection", "hutchison",
    "hutchison-tom-sky", "math", "mathiew", "norman-patricia-ai-email", "science", "vector-functions-problems-plus",
    "spherical-harmonics", "math-qa", "sequences-series", "vectors", "vector-functions",
    # emitted by mes.fm/hutchison/build.mjs (hub + section pages)
    "hutchison-posts", "hutchison-videos", "highlights", "articles", "hutchison-debunking-debunkers",
    "hutchison-news", "hutchison-unedited-footage", "hutchison-interviews", "cold-fusion-lenr",
    "hutchison-livestreams",
}

# site dir -> (site label, tail options longest -> shortest)
SITES = {
    "bmicalculator": ("BMI Calculator", [
        "Try the free BMI Calculator on MES.fm to check your body mass index, BMI chart and healthy weight range.",
        "Use the free BMI Calculator on MES.fm to check your body mass index in seconds.",
        "Free BMI Calculator and health tips on MES.fm.",
        "Free BMI Calculator on MES.fm.",
    ]),
    "gradecalculator": ("Grade Calculator", [
        "Try the free Grade Calculator on MES.fm to work out your final grade, weighted average and the score you need on your exam.",
        "Use the free Grade Calculator on MES.fm to work out your final grade and weighted average.",
        "Free Grade Calculator and study tips on MES.fm.",
        "Free Grade Calculator on MES.fm.",
    ]),
    "mortgagecalculator": ("Mortgage Calculator", [
        "Try the free Mortgage Calculator on MES.fm to estimate your monthly payment, total interest and the full cost of your home loan.",
        "Use the free Mortgage Calculator on MES.fm to estimate monthly payments and total interest.",
        "Free Mortgage Calculator and home tips on MES.fm.",
        "Free Mortgage Calculator on MES.fm.",
    ]),
    "percentagecalculator": ("Percentage Calculator", [
        "Try the free Percentage Calculator on MES.fm to work out percentages, percent change and percent difference instantly.",
        "Use the free Percentage Calculator on MES.fm to work out any percentage instantly.",
        "Free Percentage Calculator and math help on MES.fm.",
        "Free Percentage Calculator on MES.fm.",
    ]),
    "timer": ("Timer", [
        "Use the free online Timer on MES.fm for a countdown, stopwatch or alarm that runs right in your browser.",
        "Free online countdown Timer and stopwatch on MES.fm, no download needed.",
        "Free online Timer on MES.fm.",
    ]),
    "inflationcalculator": ("Inflation Calculator", [
        "Try the free Inflation Calculator on MES.fm to see how prices and the value of money change between any two years.",
        "Use the free Inflation Calculator on MES.fm to compare the value of money over time.",
        "Free Inflation Calculator on MES.fm.",
    ]),
    "youtubemoney": ("YouTube Money Calculator", [
        "Try the free YouTube Money Calculator on MES.fm to estimate how much revenue a channel can earn from its views.",
        "Use the free YouTube Money Calculator on MES.fm to estimate a channel's earnings.",
        "Free YouTube Money Calculator on MES.fm.",
    ]),
    "gpacalculator": ("GPA Calculator", [
        "Try the free GPA Calculator on MES.fm to work out your grade point average on a 4.0 or 4.33 scale.",
        "Use the free GPA Calculator on MES.fm to work out your grade point average.",
        "Free GPA Calculator on MES.fm.",
    ]),
    "pokemongocalculator": ("Pokemon Go Calculator", [
        "Try the free Pokemon Go Calculator on MES.fm to plan your levels, XP and evolutions.",
        "Free Pokemon Go Calculator on MES.fm.",
    ]),
    "vatcalculator": ("VAT Calculator", [
        "Try the free VAT Calculator on MES.fm to add or remove value added tax at any rate.",
        "Free VAT Calculator on MES.fm.",
    ]),
    "memes": ("Math Easy Solutions", [
        "Browse more funny math memes, puzzles, free calculators and video tutorials at Math Easy Solutions (MES.fm).",
        "More funny math memes, puzzles and free calculators at Math Easy Solutions (MES.fm).",
        "More math memes at Math Easy Solutions (MES.fm).",
        "Math memes on MES.fm.",
    ]),
    "puzzles": ("Math Easy Solutions", [
        "Try it yourself, then check the solution and browse more math puzzles and riddles at Math Easy Solutions (MES.fm).",
        "Try more math puzzles and riddles at Math Easy Solutions (MES.fm).",
        "More math puzzles on MES.fm.",
    ]),
}

# category directory (or top-level dir) -> phrase used after the title when the page has no real description
CATEGORY_PHRASE = {
    "memes": "a funny math meme",
    "interesting-facts": "an interesting fact",
    "dream-homes": "a dream home feature for mortgage shoppers",
    "financial-advice": "a financial advice article for home buyers",
    "study-tips": "a study tip for students",
    "health-tips": "a health tip",
    "sports": "a sports BMI article",
    "inspirational-quotes": "an inspirational quote",
    "money-facts": "a money fact about inflation and the economy",
    "youtubers": "a YouTuber earnings profile",
}

# Pages written by hand (path relative to mes.fm/), for pages a template cannot describe well.
HAND_WRITTEN = {
    "index.html": "Math Easy Solutions (MES.fm): the one stop for math video tutorials, funny math memes, puzzles, free online calculators and all things math.",
    "calculators.html": "Free online calculators from Math Easy Solutions: percentage, mortgage, BMI, grade, GPA, inflation, VAT, YouTube money, Pokemon Go and more.",
    "tools.html": "Free online tools from Math Easy Solutions: speed reader, LaTeX render, timezone converter, symbol and emoji copiers, gematria and more.",
    "memes.html": "Funny math memes from Math Easy Solutions: cartoons, jokes and clever graphs that make learning math fun. Browse and share your favorites.",
    "puzzles.html": "Math puzzles and riddles from Math Easy Solutions: matchsticks, triangles, fractions, missing squares and more, each with a full solution.",
    "puzzles/1.html": "Math puzzles and riddles from Math Easy Solutions: matchsticks, triangles, fractions, missing squares and more, each with a full solution.",
    "puzzles/2.html": "More math puzzles and riddles from Math Easy Solutions, from matchstick riddles to missing squares, each with a full step-by-step solution.",
    "mobile-apps.html": "Mobile apps from Math Easy Solutions. The original apps are being rebuilt and republished, so check back for the latest links.",
    "contact.html": "Contact Math Easy Solutions (MES.fm) with questions, feedback, corrections or ideas for new math videos, calculators and tools.",
    "privacy-policy.html": "Privacy policy for Math Easy Solutions (MES.fm): how the site and its calculators collect, use, maintain and disclose information from visitors.",
    "donate.html": "Help keep Math Easy Solutions running and providing breakthrough research by donating. Every contribution supports new videos and tools.",
    "stats.html": "MES Stats: the most viewed pages across mes.fm and its calculators and tools, updated live so you can see what people are reading.",
    "links/index.html": "MES Links: every relevant MES link, note and reference in one page, covering math videos, calculators, tools and research.",
    "gematria/index.html": "MES Gematria Calculator: calculate Ordinal and Sumerian gematria values for any word or phrase, with a downloadable Excel spreadsheet.",
    "earth-curvature-calculator/index.html": "MES Earth Curvature Calculator: enter a distance in kilometers or miles to calculate how much the Earth curves over that distance.",
    "impermanent-loss-calculator/index.html": "MES Impermanent Loss Calculator: calculate impermanent loss in a liquidity pool and compare it with simply holding one or both assets.",
    "unit-conversion/index.html": "MES Unit Conversion Calculator: convert feet to meters, mph to km/h, pounds to kilograms and many more units quickly and accurately.",
    "sjwkeyboard/index.html": "Being a SJW is tough work; let the Social Justice Warrior Keyboard do the heavy lifting. A joke keyboard from Math Easy Solutions.",
    "chatgpt/calculator/index.html": "MES ChatGPT Calculator: a simple online calculator that adds two numbers and shows the sum. A quick, free tool from Math Easy Solutions.",
    "gpacalculator/index.html": "Use this GPA Calculator to calculate your grade point average using a 4.33 or 4.0 scale. Free, fast and easy to use on MES.fm.",
    "gpacalculator/gpa-scale-4.html": "See the 4.0 GPA scale used by our GPA Calculator, with the letter grade, percentage and grade point equivalents in one table.",
    "gpacalculator/gpa-scale-433.html": "See the 4.33 GPA scale used by our GPA Calculator, with the letter grade, percentage and grade point equivalents in one table.",
    "gpacalculator/grade-point-average.html": "Learn what Grade Point Average (GPA) really means, how it is calculated and how to use the free GPA Calculator on MES.fm.",
    "gpacalculator/tutorial.html": "Learn how the GPA Calculator works with this video tutorial, then use the free GPA Calculator on MES.fm on your own grades.",
    "inflationcalculator/index.html": "This Inflation Calculator calculates a country's inflation rate between two different years, so you can see how prices have changed.",
    "vatcalculator/index.html": "Use this VAT Calculator to calculate value added tax from a net value at a specific VAT rate. Free and easy to use on MES.fm.",
    "youtubemoney/index.html": "Use this YouTube Money Calculator to calculate how much revenue YouTubers can make from their views. Free and easy on MES.fm.",
    "pokemongocalculator/experience-chart.html": "See the Pokemon Go experience chart from level 1 to 40, with the XP needed for each level, from the Pokemon Go Calculator on MES.fm.",
    "inflationcalculator/money-facts.html": "Money facts from the Inflation Calculator on MES.fm: interesting stories about inflation, banking and the value of money over time.",
    "911djw/index.html": "MES 9/11 Truth Links: the collection of Math Easy Solutions videos and articles on the real 9/11 truth, gathered in one place.",
    "president-stephen-a-smith/index.html": "MES clip of ESPN's Stephen A. Smith possibly alluding to a presidential bid, mirrored from the Hive blockchain by Math Easy Solutions.",
    "ashton-forbes-letter/index.html": "Highlights from the January 2024 letter praising Ashton Forbes for his MH370 work, mirrored from the Hive blockchain by MES.",
    "cadd-stablecoin-solana/index.html": "Canada's first ever stablecoin is live on Solana as $CADD. Read the announcement, mirrored from the Hive blockchain and Telegram.",
    "lightning-sky/index.html": "Lightning lighting up the entire sky, filmed in Richmond, BC, Canada. Watch the video, mirrored from the Hive blockchain by Mathiew.",
    "tesla-coil/index.html": "Build Log 1: Tesla Coil, Faraday Cage, Ground Rod. A running build log of MES science experiments, mirrored from the Hive blockchain.",
    "hutchison-health-aug22-2026/index.html": "Prayers up for John Hutchison: a health update on the Hutchison Effect researcher, mirrored from the Hive blockchain and Telegram.",
    "livestream-140-trailer-911-real-avengers/index.html": "Trailer for MES Livestream 140: 9/11, The Real Avengers by Chris Shak. Watch the trailer, mirrored from the Hive blockchain and Telegram.",
    "911-3d-print-pin/index.html": "MES's niece made him a 9/11 pin with her 3D printing pen. A heartwarming family story, mirrored from the Hive blockchain and Telegram.",
    "ufo/index.html": "MES Science Experiments: a running build log of Tesla coil experiments and progress, with videos and notes from Math Easy Solutions.",
    # Four pages whose <meta name="description"> was corrupted by HTTrack: the whole article body was stuffed into the
    # attribute and the closing quote is missing, so the tag swallows the next <meta> (twitter:card). Rewritten in full.
    "gradecalculator/study-tips/mistakes-grow-your-brain.html": "Studies show your brain grows when you make mistakes, even ones you don't notice. Learn why mistakes help you learn more when studying for exams and math tests.",
    "inflationcalculator/money-facts/jeff-bezos-amazon-cia-and-the-washington-post.html": "How billionaire Jeff Bezos, Amazon, the CIA and The Washington Post are financially tied together, from a $600 million AWS cloud contract to a $250 million purchase.",
    "mortgagecalculator/dream-homes/tepoztlan-lounge-in-tepoztlan-mexico.html": "The Tepoztlan Lounge near Mexico City, designed by Cadaval & Sol\u00e0-Morales, is a concrete lounge built around living trees as a tribute to nature. A dream home feature.",
    "percentagecalculator/interesting-facts/40-of-the-world-is-free.html": "According to Freedom House, only about 40% of the world's countries are free. See what the 2016 report says about freedom of expression, politics and economics.",
    "math-qa-71-stats/index.html": "MES Math Q/A 71 livestream stats: views, watch time and audience numbers for the livestream. Mirrored from Hive and Telegram.",
}


def clean(s):
    return re.sub(r"\s+", " ", html.unescape(s)).strip()


def sentence(s):
    s = s.strip()
    return s if s[-1:] in ".!?" or s[-2:] in (";)", ":)") else s + "."


def esc(s):
    return html.escape(s, quote=True)


def pick_tail(lead, tails):
    """Longest tail that keeps the total <= MAX_LEN; else the shortest tail that reaches MIN_LEN; else the longest."""
    fits = [t for t in tails if len(lead) + 1 + len(t) <= MAX_LEN]
    if fits:
        return fits[0]
    ok = [t for t in tails if len(lead) + 1 + len(t) >= MIN_LEN]
    return ok[-1] if ok else tails[0]


def build(rel, old, page_title, category_dir, title_parts):
    if rel in HAND_WRITTEN:
        return HAND_WRITTEN[rel]
    parts = rel.split("/")
    site = parts[0]
    if site not in SITES:
        return None
    label, tails = SITES[site]
    is_solution = parts[-1] == "solution.html"

    if is_solution:
        base = re.sub(r"\s*\(SOLUTION\)\s*$", "", page_title)
        lead = sentence(f'Solution and answer to the math puzzle "{base}" from Math Easy Solutions')
        tails = ["See the full step-by-step answer, then try more math puzzles and riddles at Math Easy Solutions (MES.fm).",
                 "See the full answer, then try more math puzzles on MES.fm.",
                 "More math puzzles on MES.fm."]
    elif old and not BOILER_RE.search(old):
        # a real description: keep it, prefixed by the title if it does not already mention it
        t = page_title.rstrip(".!? ")
        lead = sentence(old if t.lower() in old.lower() or len(parts) == 2 and category_dir is None else f"{t} - {old}")
    else:
        t = page_title.rstrip(". ")
        phrase = CATEGORY_PHRASE.get(category_dir)
        lead = sentence(f"{t} - {phrase}" if phrase else f"{t} - {label}")
    if len(lead) >= MIN_LEN:
        return lead
    return f"{lead} {pick_tail(lead, tails)}"


def process(path, apply):
    rel = os.path.relpath(path, ROOT).replace(os.sep, "/")
    top = rel.split("/")[0]
    if top in GENERATED or "_http" in rel or "template" in rel or "node_modules" in rel:
        return None
    src = open(path, encoding="utf-8", errors="surrogateescape").read()
    m = META_RE.search(src)
    old_raw = None
    old = ""
    if m:
        c = CONTENT_RE.search(m.group(0))
        old_raw = c.group(2) if c else ""
        old = clean(old_raw)
    malformed = bool(m) and m.group(0).count('"') % 2 == 1
    if old and len(old) >= MIN_LEN and not malformed:
        return None
    tm = TITLE_RE.search(src)
    title_parts = [clean(p) for p in clean(tm.group(1)).split("|")] if tm else []
    if title_parts and title_parts[0].startswith("Page Not Found"):
        return None
    ogm = OG_TITLE_RE.search(src)
    page_title = clean(ogm.group(2)) if ogm else (title_parts[0] if title_parts else "")
    parts = rel.split("/")
    category_dir = parts[1] if len(parts) == 3 else (parts[0] if len(parts) == 2 and parts[0] == "memes" else None)
    new = build(rel, old, page_title, category_dir, title_parts)
    if not new or new == old:
        return None
    new_attr = esc(new)
    out = src
    if m and malformed:
        # Unterminated attribute (may run past several ">" characters): each corrupted tag really extends to the start
        # of the next <meta>, so cut from the tag's opening to there and write clean tags in their place.
        for prop, attr in (("description", "name"), ("og:description", "property"), ("twitter:description", "name")):
            start = re.search(r'<meta\s+%s=["\']%s["\']\s+content=' % (attr, re.escape(prop)), out)
            if not start:
                continue
            end = out.find("<meta", start.end())
            if end < 0:
                return ("SKIP-no-next-meta", rel, old, new)
            gap = out[start.start():end]
            out = out[:start.start()] + f'<meta {attr}="{prop}" content="{new_attr}">' + gap[len(gap.rstrip()):] + out[end:]
    elif m:
        tag = m.group(0)
        c = CONTENT_RE.search(tag)
        new_tag = tag[:c.start(2)] + new_attr + tag[c.end(2):]
        out = out.replace(tag, new_tag, 1)
        if old_raw:
            for prop in ("og:description", "twitter:description"):
                out = re.sub(
                    r'(<meta\s+(?:property|name)=["\']%s["\']\s+content=["\'])%s(["\'])' % (re.escape(prop), re.escape(old_raw)),
                    lambda mm: mm.group(1) + new_attr + mm.group(2), out)
    else:
        ins = f'<meta name="description" content="{new_attr}">\n'
        tm2 = TITLE_RE.search(out)
        if not tm2:
            return ("SKIP-no-title", rel, old, new)
        out = out[:tm2.end()] + "\n  " + ins.rstrip("\n") + out[tm2.end():]
    if apply:
        with open(path, "w", encoding="utf-8", errors="surrogateescape") as f:
            f.write(out)
    return ("OK", rel, old, new)


def main():
    apply = "--apply" in sys.argv
    changed, skipped = [], []
    for path in sorted(glob.glob(os.path.join(ROOT, "**", "*.html"), recursive=True)):
        r = process(path, apply)
        if r is None:
            continue
        (changed if r[0] == "OK" else skipped).append(r)
    lens = [len(r[3]) for r in changed]
    for _, rel, old, new in changed:
        if "-v" in sys.argv:
            print(f"{rel}\n  - {old!r}\n  + {new!r} ({len(new)})")
    print(f"{'Updated' if apply else 'Would update'} {len(changed)} pages"
          + (f"; new lengths min {min(lens)} / max {max(lens)}; {sum(1 for l in lens if l < MIN_LEN)} still < {MIN_LEN}" if lens else ""))
    for s in skipped:
        print("SKIPPED", s[1], s[0])
    if not apply:
        print("Dry run. Re-run with --apply to write.")


if __name__ == "__main__":
    main()
