#!/usr/bin/env python3
"""
Collapse the shared navbar's "Calculators ▼" / "Tools ▼" dropdown
submenus repo-wide into plain links to the hub pages.

Those dropdowns hand-curate a handful of individual calculators/tools (each
ending in a "More..." link to the hub page anyway), duplicating -- and
drifting out of sync with -- the categorized, searchable hub pages that
organize_hub_cards.py built at mes.fm/calculators and mes.fm/tools. They also
make the hamburger menu very tall on phones (reported live on the Percentage
Calculator iOS app, whose hamburger menu is the same shared navbar). Replacing
each dropdown with a single link to its hub page removes duplicated
maintenance and shortens the menu; the hub pages are strictly more capable
navigation now.

NOT touched: other same-looking dropdowns that aren't site-category nav --
"Formulas" (~200 grade/mortgage/etc. pages, links to that calculator's own
formula reference) and "GPA Scales" (5 gpacalculator pages, country GPA scale
tables). Matched by label ("Calculators" / "Tools" exactly), so those never
match.

Each dropdown is a single, non-nested <ul class="navbar__dropdown-container
hide"> (its own <li> items are plain <a>...</a></li>, no inner <ul>), so a
non-greedy DOTALL match from the trigger <li> through the first following
</ul></li> is safe and always lands on the dropdown's own closing tag.

Patches every *.html under the repo (except percentagecalculator-app/www/,
generated by build-www.py from mes.fm/percentagecalculator/index.html --
fixing the source and rebuilding carries this in) plus the seven build.mjs
generators that emit the same navbar block, so a rebuild doesn't revert it.

Idempotent: a page with no remaining "navbar__link--dropdown\">Calculators"
(or Tools) text no longer matches. Dry-runs by default; pass --apply to write.
"""

import argparse
import os
import re
import sys
from collections import Counter

ROOT = os.path.expanduser("~/Documents/GitHub/mes.fm")

SKIP_DIRS = {
    "_http_", "_https_", ".git", "node_modules", "__pycache__",
    "percentagecalculator-app",
}
SKIP_FILES = {os.path.join(ROOT, "index.html")}

HUB_HREF = {"Calculators": "/calculators", "Tools": "/tools"}


def block_re(label: str) -> re.Pattern:
    return re.compile(
        r'<li class="navbar__item"><span class="navbar__link '
        r'navbar__link--dropdown">' + re.escape(label) +
        r'<span class="dropdown-symbol">&#9660;</span></span>'
        r'.*?</ul>\s*</li>',
        re.DOTALL,
    )


REPLACEMENT = {
    label: (
        '<li class="navbar__item"><a class="navbar__link" href="%s">%s</a></li>'
        % (href, label)
    )
    for label, href in HUB_HREF.items()
}


def collapse(html: str) -> tuple[str, Counter]:
    counts = Counter()
    for label in HUB_HREF:
        html, n = block_re(label).subn(REPLACEMENT[label], html)
        counts[label] += n
    return html, counts


def iter_files():
    for dirpath, dirnames, filenames in os.walk(ROOT):
        dirnames[:] = [d for d in dirnames if d not in SKIP_DIRS]
        for name in filenames:
            if name.endswith((".html", ".mjs")):
                path = os.path.join(dirpath, name)
                if path not in SKIP_FILES:
                    yield path


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true")
    ap.add_argument("-v", action="store_true")
    args = ap.parse_args()

    total = Counter()
    changed_files = 0
    for path in sorted(iter_files()):
        try:
            html = open(path, encoding="utf-8").read()
        except (UnicodeDecodeError, IsADirectoryError):
            continue
        new_html, counts = collapse(html)
        if new_html == html:
            continue
        changed_files += 1
        total.update(counts)
        rel = os.path.relpath(path, ROOT)
        if args.v:
            print("  %s: Calculators x%d, Tools x%d"
                  % (rel, counts["Calculators"], counts["Tools"]))
        if args.apply:
            open(path, "w", encoding="utf-8").write(new_html)

    print("%s%d files %s (Calculators x%d, Tools x%d)"
          % ("" if args.apply else "[dry run] ", changed_files,
             "changed" if args.apply else "would change",
             total["Calculators"], total["Tools"]))
    if not args.apply:
        print("Re-run with --apply to write.")


if __name__ == "__main__":
    sys.exit(main())
