#!/usr/bin/env python3
"""
Shorten <meta name="description"> text that is over 320 characters (Site Index "Description over 320 chars", 134 pages on 2026-10-06).

About 130 article pages (BMI health tips, puzzles, ...) have the whole article body stuffed into the description. Google cuts it
at ~155-160 characters anyway, so the extra text only bloats the HTML (and og:description / twitter:description, which repeat it).
The new text is the page's own opening, cut at the last sentence end that fits in LIMIT characters, else at a word boundary with an
ellipsis. og:description / twitter:description are kept in sync when they were identical to the old description. Pages generated by a
build.mjs / build_math_qa_mirrors.py (improve_meta_descriptions.GENERATED) are skipped: fix those in their generators.
Idempotent (a description <= 320 is left alone); **dry-runs by default (-v lists pages), `--apply` writes.**
"""
import glob
import html
import os
import re
import sys

import improve_meta_descriptions as imd

ROOT = imd.ROOT
TRIGGER = 320   # only descriptions longer than this are touched
LIMIT = 158     # how long the new description may be
FLOOR = 100     # a sentence end earlier than this is not used (too short for Bing)
META_RE, CONTENT_RE = imd.META_RE, imd.CONTENT_RE


def shorten(text):
    t = re.sub(r"\s+", " ", html.unescape(text)).strip()
    if len(t) <= LIMIT:
        return t
    cut = t[:LIMIT + 1]
    best = max((m.end() for m in re.finditer(r"[.!?](?=\s|$)", cut)), default=0)
    if best >= FLOOR:
        return t[:best].strip()
    cut = t[:LIMIT - 1]
    cut = cut[:cut.rfind(" ")] if " " in cut else cut
    return cut.rstrip(" ,;:-–—") + "…"


def esc(s):
    return s.replace("&", "&amp;").replace('"', "&quot;")


def main():
    apply_ = "--apply" in sys.argv
    verbose = "-v" in sys.argv
    changed = 0
    for path in sorted(glob.glob(os.path.join(ROOT, "**", "*.html"), recursive=True)):
        rel = os.path.relpath(path, ROOT)
        if "/_http" in "/" + rel or rel.startswith("_http"):
            continue
        top = rel.split(os.sep)[0]
        if top in imd.GENERATED or rel.split(os.sep)[0] + "/" in imd.GENERATED:
            continue
        text = open(path, encoding="utf-8").read()
        if "TOOL-DARK:START" in text:   # a build_tool_apps.py page: its description lives in the APPS table
            continue
        m = META_RE.search(text)
        if not m:
            continue
        cm = CONTENT_RE.search(m.group(0))
        if not cm or len(html.unescape(cm.group(2))) <= TRIGGER:
            continue
        old_raw = cm.group(2)
        new = esc(shorten(old_raw))
        out = text.replace(m.group(0), m.group(0).replace(old_raw, new, 1), 1)
        # keep og / twitter descriptions in step when they repeated the old text
        for rx in (r'(<meta\s+property=["\']og:description["\']\s+content=)(["\'])(.*?)\2', r'(<meta\s+name=["\']twitter:description["\']\s+content=)(["\'])(.*?)\2'):
            out = re.sub(rx, lambda mm: mm.group(1) + mm.group(2) + (new if mm.group(3) == old_raw else mm.group(3)) + mm.group(2), out, count=1, flags=re.S)
        if out != text:
            changed += 1
            if verbose:
                print("%-70s %5d -> %3d  %s" % (rel, len(html.unescape(old_raw)), len(html.unescape(new)), html.unescape(new)[-40:]))
            if apply_:
                open(path, "w", encoding="utf-8").write(out)
    print("%d pages %s" % (changed, "changed" if apply_ else "would change (dry run -- pass --apply)"))


if __name__ == "__main__":
    main()
