// Content for mes.fm/hutchison and its section pages. Hand-maintained; read by build.mjs.
//
// mes.fm/hutchison used to mirror the Hive post @mes/hutchisoneffect (a single long article
// holding every section). It is now a tile hub like mes.fm/math, and each section of that
// article lives on its own page (see PAGES in build.mjs). This file is the new source of
// truth for those sections -- the Hive post is no longer fetched. To add something, drop an
// entry at the TOP of the right section (newest first) and run `npm run build`.
//
// Two kinds of item:
//   { title, image, links: [[label, href], ...] }
//       Everything spelled out (the shape the Hive article used: title, thumbnail, one row of
//       platform links). The card links to the item's first mes.fm link, else its Hive/peakd
//       link, else its first link; List View shows the whole row.
//   { href, title }
//       A mes.fm mirror page (or peakd post). The thumbnail and its "Watch on:" row are
//       scraped from the target at build time and cached in link-meta.json.
// `standalone: true` (with href + title) is a whole-playlist link shown as a plain line above the
// grid rather than as a card.

export const SECTIONS = [
  {
    id: "hutchison-posts",
    title: "Posts and Updates",
    items: [
      { href: "https://mes.fm/hutchison-article-balloons", title: "John Hutchison's First Newspaper Appearance: Balloons Over Grouse Mountain" },
      { href: "https://mes.fm/hutchison-health-sept6-2026", title: "John Hutchison is coming home — health update" },
      { href: "https://mes.fm/hutchison-health-sept5-2026", title: "Prayers up for John Hutchison, again — health update" },
      { href: "https://mes.fm/bought-911-hutchison-shirt", title: "Someone bought a 9/11 DJW Book shirt and Hutchison Effect shirt" },
      { href: "https://mes.fm/hutchison-health-aug22-2026", title: "Prayers up for John Hutchison — health update" },
    ],
  },
  {
    id: "hutchison-videos",
    title: "Videos",
    items: [
      { href: "https://mes.fm/hutchison-levitating-can-live", title: "Hutchison Effect: Plastic Can Levitates and Video is Played Back LIVE" },
      { href: "https://mes.fm/hutchison-effect-steel-molybdenum", title: "Hutchison Effect: George Hathaway and John Alexander Discuss Crumbling Steel & Bent Molybdenum Rods" },
      { href: "https://mes.fm/livestream-66-trailer", title: "Trailer for MES Livestream 66: Rare Hutchison Effect Footage" },
    ],
  },
  {
    id: "highlights",
    title: "Highlights",
    items: [
      { title: "Hutchison Effect: Plastic Can Levitates and Video is Played Back LIVE",
        image: "https://images.3speak.tv/images/1790118173447-fc686c3b9719153c.webp",
        links: [["Screenshots", "https://mes.fm/hutchison-levitating-can-live"], ["3Speak", "https://3speak.tv/watch?v=mes/hutchison-effect-plastic-ca-593"], ["YouTube", "https://youtu.be/84_R56cjqMQ"], ["Telegram", "https://t.me/meslinks/35568"], ["BitChute", "https://www.bitchute.com/video/8jwVZeAXX9pO/"], ["Odysee", "https://odysee.com/@mes:8/Hutchison-Effect-Can-Levitates-Live-Playback:a"], ["Rumble", "https://rumble.com/v7fv5tq-hutchison-effect-plastic-can-levitates-and-video-is-played-back-live.html"]] },
      { title: "Hutchison Effect: 19 lb bushing levitates with linearly increasing acceleration – \"Hyperforce”",
        image: "https://images.3speak.tv/images/1785445828290-a0571387cad1a33c.webp",
        links: [["Screenshots", "https://peakd.com/hive-128780/@mes/hutchison-effect-19-lb-bush-939"], ["3Speak", "https://3speak.tv/watch?v=mes/hutchison-effect-19-lb-bush-939"], ["YouTube", "https://youtu.be/7v_AYRCw5nU"], ["Telegram", "https://t.me/meslinks/35272"], ["BitChute", "https://www.bitchute.com/video/H9mhJfY5p8Pj/"], ["Odysee", "https://odysee.com/@mes:8/Hutchison-Effect-3rd-derivative-Hyperforce:b"], ["Rumble", "https://rumble.com/v7dp0c0-hutchison-effect-19-lb-bushing-levitates-with-linearly-increasing-accelerat.html"], ["Excel file", "https://1drv.ms/x/c/88862ef47bcaf6cd/IQB9ztjdln5gQ5CzQ_P6ynxXAdUBzocWCAOwM83kiw03sAo"]] },
      { title: "Hutchison Effect Compilation from 1988 to 1989",
        image: "https://files.peakd.com/file/peakd-hive/mes/23tmFRQJwjwVwhFCsH1aBV5igGtMKokxPw4yNokw66Zz4KKuttWGYqCMiP7T9cZPbfMPP.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/lwjfblia"], ["3Speak", "https://3speak.tv/watch?v=mes/lwjfblia"], ["YouTube", "https://youtu.be/ZWHTIA1eL5k"], ["BitChute", "https://old.bitchute.com/video/DkkgeRlT671w/"], ["Odysee", "https://odysee.com/Hutchison-Effect-Compilation-1988-1989:a06d346f96f2af32a903ad10eb5e345aae599ed4"], ["Rumble", "https://rumble.com/v6vj2rz-hutchison-effect-compilation-from-1988-to-1989.html"]] },
      { title: "Hutchison Effect: Timelapse of 5 Hours of Footage into 5 Minutes Reveals RARE Effects",
        image: "https://files.peakd.com/file/peakd-hive/mes/23wgKzP3nSVbCHkzPbgkpbHx3DY3gaVAjzNMEvY9vXL8JqVz2eTtH5XPkjfiDwDCZSSqy.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/tznpkpee"], ["3Speak", "https://3speak.tv/watch?v=mes/tznpkpee"], ["YouTube", "https://youtu.be/zmdVFzpOFhs"], ["BitChute", "https://old.bitchute.com/video/0JWzR6mH2E76/"], ["Odysee", "https://odysee.com/Hutchison-Effect-Timelapse-Jack-Houck:b75de0b42b89ab87c0f4acc79403ce518e96d8de"], ["Rumble", "https://rumble.com/v6s7uuv-hutchison-effect-timelapse-of-5-hours-of-footage-into-5-minutes-reveals-rar.html"]] },
      { title: "Hutchison Effect: Clorox Bottle Compresses and Decompresses",
        image: "https://files.peakd.com/file/peakd-hive/mes/23uFPdq8y2bqcMTiDiwZ6FpHeRZZWtPz3DKtwHmJRBXruGq94WeCP2TYpGWKk58hHb5Rb.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/wpjnaiyq"], ["3Speak", "https://3speak.tv/watch?v=mes/wpjnaiyq"], ["YouTube", "https://youtu.be/amENrIgtHvg"], ["BitChute", "https://old.bitchute.com/video/cq4iUEcp9cTk/"], ["Odysee", "https://odysee.com/@mes:8/Hutchison-Effect-Bottle-Compresses:b"], ["Rumble", "https://rumble.com/v6rjddd-hutchison-effect-clorox-bottle-compresses-and-decompresses.html"]] },
      { title: "Hutchison Effect: Steel Rod Bends, Levitates, and Flies Upwards",
        image: "https://files.peakd.com/file/peakd-hive/mes/23wMaSH2ej21cjpqZJXK79eBg2zdBQQVsRugnAd3MmbLs8CwBJGSmw8NAcJm7sYbGWNkA.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/zmxodcgi"], ["3Speak", "https://3speak.tv/watch?v=mes/zmxodcgi"], ["YouTube", "https://youtu.be/Q5HLI2HjsB0"], ["BitChute", "https://www.bitchute.com/video/lWVyczVeeKcc"], ["Odysee", "https://odysee.com/@mes:8/Hutchison-Effect-Steel-Rod-Bends:a"], ["Rumble", "https://rumble.com/v6qlgcw-hutchison-effect-steel-rod-bends-levitates-and-flies-upwards.html"]] },
      { title: "Hutchison Effect: Solid Stainless Steel Cylinder splits apart like Jelly",
        image: "https://files.peakd.com/file/peakd-hive/mes/23wgHvq5dWdTN6wx7AT2zRXoXAxStMUCPKY5FBira2X4jbPQRzeur5jeGKvX12Asx1JsG.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/egladafi"], ["3Speak", "https://3speak.tv/watch?v=mes/egladafi"], ["YouTube", "https://youtu.be/TtqWmVWZ8Us"], ["BitChute", "http://bitchute.com/video/Pd0H23GYigww/"], ["Odysee", "https://odysee.com/Hutchison-Effect-Steel-Cylinder-Jelly:5f91144f604af55ce042ff4e886bd508b25c5f61"], ["Rumble", "https://rumble.com/v6jso6s-hutchison-effect-solid-stainless-steel-cylinder-splits-apart-like-jelly.html"]] },
      { title: "Hutchison Effect: High Frequency Electrical Discharge Fires on Plastic Boat",
        image: "https://files.peakd.com/file/peakd-hive/mes/23y94QLvgQBm5e6yC4V1zQ1gJLEPPtKy8iGVrUXYNx2TDje6aZXijKxadTwMNoKsyBbWB.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/sbjduqfl"], ["Screenshots", "https://peakd.com/hive-128780/@mes/okvxltmy"], ["3Speak", "https://3speak.tv/watch?v=mes/sbjduqfl"], ["YouTube", "https://youtu.be/E_AiyTHmonA"], ["BitChute", "https://old.bitchute.com/video/hTU6E3I4WsMz/"], ["Odysee", "https://odysee.com/Hutchison-Effect-Electrical-Fires-Boat:0229255436dee7944186fb0a00b20661e23c093d"], ["Rumble", "https://rumble.com/v6q31wc-hutchison-effect-high-frequency-electrical-discharge-fires-on-plastic-boat.html"]] },
      { title: "Hutchison Effect: High Frequency Radio Waves Cause Water to Foam Up",
        image: "https://files.peakd.com/file/peakd-hive/mes/23xAbqQxHtTXL1m1gUwHnAYuzjcqRh555LQSbjez2vJfQ55y3q5cjjVX9RFEY9N49hKu7.JPEG",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/pirokkna"], ["Screenshots", "https://peakd.com/hive-128780/@mes/okvxltmy"], ["3Speak", "https://3speak.tv/watch?v=mes/pirokkna"], ["YouTube", "https://youtu.be/iWd_ubhsGoU"], ["BitChute", "https://old.bitchute.com/video/KM1D29sR0ken/"], ["Odysee", "https://odysee.com/@mes:8/Hutchison-Effect-Water-Foam-Boat:3"], ["Rumble", "https://rumble.com/v6q5i1o-hutchison-effect-high-frequency-radio-waves-cause-water-to-foam-up.html"]] },
      { title: "Hutchison Effect: 1 Hour of the Famous Plastic Boat on Water Experiment",
        image: "https://files.peakd.com/file/peakd-hive/mes/23tvgSmo4ftvmvKDHcKhcsCTkxE66kd1WJJ8HvtGpwXWDkZ4egPJs5vsq43g41Qgchmx1.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/okvxltmy"], ["3Speak", "https://3speak.tv/watch?v=mes/okvxltmy"], ["YouTube", "https://youtu.be/hBfqjBSItj0"], ["BitChute", "https://old.bitchute.com/video/ihVuR4bq2FiD/"], ["Odysee", "https://odysee.com/Hutchison-Effect-Plastic-Boat:9d7d735e43e9583286ff8c7f1045fe2d497cf63e"], ["Rumble", "https://rumble.com/v6pdyix-hutchison-effect-1-hour-of-the-famous-plastic-boat-on-water-experiment.html"]] },
      { title: "Hutchison Effect: Solid Metal Rod Splits apart like Jelly",
        image: "https://files.peakd.com/file/peakd-hive/mes/23tmDmV9k9nW3wyjjJ6xVUJyqmmJC7tZD4v5odbeqLDsa9nyj7JR4oBtvmePb8mPyW1YN.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/qvqnthrh"], ["3Speak", "https://3speak.tv/watch?v=mes/qvqnthrh"], ["YouTube", "https://youtu.be/BWCuM4GQlgc"], ["BitChute", "https://bitchute.com/video/fwO5FhtuXy7t/"], ["Odysee", "https://odysee.com/Hutchison-Effect-Metal-Jelly:38ff0793c1ba57548ea206f857f215a68a915d06"], ["Rumble", "https://rumble.com/v6i5q9m-hutchison-effect-solid-metal-rod-splits-apart-like-jelly.html"]] },
      { title: "Hutchison Effect: 80-pound Mill Ball Levitating Up and Down for 10 Minutes",
        image: "https://files.peakd.com/file/peakd-hive/mes/23u5tdp4wQogynKFRjke6sZayQuD2NNH3z7ihjXpcpy87zFdzCcZacRmVfQiCcmHpCXEM.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/nnxpbnke"], ["3Speak", "https://3speak.tv/watch?v=mes/nnxpbnke"], ["YouTube", "https://youtu.be/C2FbX_xWXaQ"], ["BitChute", "https://bitchute.com/video/Rd6p8wkhx4id/"], ["Odysee", "https://odysee.com/@mes:8/Hutchison-Effect-Mill-Ball-Levitation:4"], ["Rumble", "https://rumble.com/v6bvved-hutchison-effect-80-pound-mill-ball-levitating-up-and-down-for-10-minutes.html"]] },
      { title: "Hutchison Effect: Steel Rubber Composite Cold Melting (180X Speed)",
        image: "https://files.peakd.com/file/peakd-hive/mes/23x12vcay9VBFqmJcL1ejVrXcUrCXZ5jMbhYsbstFTrYvURRdTb3hV68aGQCuRDtfuWfi.jpeg",
        links: [["Hive", "https://peakd.com/hutchisoneffect/@mes/hutchison-effect-steel-rubber-melting-short"], ["YouTube", "https://youtu.be/o90ylugSL_M"], ["BitChute", "https://bitchute.com/video/aYKuNdDrrlRl/"], ["Odysee", "https://odysee.com/Hutchison-Effect-Steel-Rubber-Cold-Melting-Short:135cd57ce78c8540e0fa21cabdb68d95bdd421b4"], ["Rumble", "https://rumble.com/v5yes8q-hutchison-effect-steel-rubber-composite-cold-melting-180x-speed.html"]] },
      { title: "Hutchison Effect: Steel Rubber Composite Cold Melting",
        image: "https://files.peakd.com/file/peakd-hive/mes/23wgFPodnECy1f1zMCY7if4Mbe1BD5FsnzcGk2B3KhNThcFdfJqSAhL46KJbqFGrcfWxf.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/hutchison-effect-steel-rubber-cold-melting"], ["YouTube", "https://youtu.be/tBTzf_WEuME"], ["BitChute", "https://bitchute.com/video/8TzJPaNzCEM1/"], ["Odysee", "https://odysee.com/@mes:8/Hutchison-Effect-Steel-Rubber-Composite:c"], ["Rumble", "https://rumble.com/v5y2z1n-hutchison-effect-steel-rubber-composite-cold-melting.html"]] },
      { title: "Hutchison Effect: Solid Block of Iron Warping and Twisting (Two Experiments)",
        image: "https://files.peakd.com/file/peakd-hive/mes/23u67TyDiLoRNjSSrjgpXuKbYf8ogHYr3kYirR3iLiDU67vECxwLH7bomGGck2ECwaxiy.jpeg",
        links: [["Hive", "https://peakd.com/@mes/dnqjqhjn"], ["3Speak", "https://3speak.tv/watch?v=mes/dnqjqhjn"], ["YouTube", "https://youtu.be/HGMdOk5a9Vk"], ["BitChute", "https://www.bitchute.com/video/c6Hd3QRO1YD3/"], ["Odysee", "https://odysee.com/@mes:8/Hutchison-Effect-Iron-Block-Two-Experiments:c"], ["Rumble", "https://rumble.com/v4x67l5-hutchison-effect-solid-block-of-iron-warping-and-twisting-two-experiments.html"]] },
      { title: "1109 by Keor Meteor: Intro: The Hutchison Effect",
        image: "https://files.peakd.com/file/peakd-hive/mes/244AAhPLEBCofvkWTk3e6W2Wui7yqxN4stRB3z1aoPMoGsLhu8d8nhqiM1EqSGzuf3BY9.jpeg",
        links: [["Hive", "https://peakd.com/hive-113182/@mes/wmyovlcv"], ["3Speak", "https://3speak.tv/watch?v=mes/wmyovlcv"], ["YouTube", "https://youtu.be/hQlPItudSSQ"]] },
      { title: "Trailer for Livestream 97: Hutchison Effect 1988 to 1989 Compilation",
        image: "https://files.peakd.com/file/peakd-hive/mes/23tbkoYJYUK6N1HtzHbdEfEn8puHKDkm9qaRkMTWyi5dPruAEduDGEuBqDCvFMFMs5ixw.png",
        links: [["YouTube", "https://youtu.be/O-KoQ3_Drag"]] },
      { title: "Trailer for Livestream 66: Rare Hutchison Effect Footage",
        image: "https://files.peakd.com/file/peakd-hive/mes/244oWj3p8Ybu9EoydUnAB6yi9d7ZLgN7yEbEEtprH6DWb7a6fA6TZUKnCK5dyXnnmoc9j.jpeg",
        links: [["YouTube", "https://youtu.be/WbvO8BbKIP0"]] },
    ],
  },
  {
    id: "articles",
    title: "Articles",
    items: [
      { title: "Hutchison Effect: Stop Motion Photos of Levitating WATER",
        image: "https://files.peakd.com/file/peakd-hive/mes/Eos1McX1hDrTwP8GUx8GhY7VsBhufMNgUygaCrcZY3W6ihMnwByRBQBKiWWfKyfBoit.png",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/hutchison-effect-levitating-water-37i"], ["Telegram", "https://t.me/meslinks/29910"], ["InLeo", "https://inleo.io/threads/view/mes/re-leothreads-yfh4z4mf"]] },
      { title: "Photos of John Hutchison's parents and grandparents!! 👫👼",
        image: "https://files.peakd.com/file/peakd-hive/mes/23wMYNDAw3oQpaPk3gkp4zyd4mwq6hstkAoZCNUmFUBu9Hpj5CG9ojCpfnNdrmToHHKua.png",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/photos-of-john-hutchisons-parents--5aq"]] },
    ],
  },
  {
    id: "hutchison-debunking-debunkers",
    title: "Debunking \"Debunkers\"",
    single: true,
    items: [
      { title: "Hutchison Effect: Debunking the \"Debunkers\" (Liars) Robert Murray-Smith and Ace Baker",
        image: "https://files.peakd.com/file/peakd-hive/mes/242Nktq4gBzhMiryTReQ8hCXywwgpx1obUvGhBiyLQKFyH6ebN46yGnUY1LCYoEqNL7qb.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/wbvdabyb"], ["3Speak", "https://3speak.tv/watch?v=mes/wbvdabyb"], ["YouTube", "https://youtu.be/Po0vWGJDu6M"], ["BitChute", "https://bitchute.com/video/DP7JfOptA756/"], ["Odysee", "https://odysee.com/@mes:8/Hutchison-Effect-Debunking-Liars-Robert-Murray-Smith-Ace-Baker:f"], ["Rumble", "https://rumble.com/v5bupqs-hutchison-effect-debunking-the-debunkers-liars-robert-murray-smith-and-ace-.html"]] },
    ],
  },
  {
    id: "hutchison-news",
    title: "News Reels",
    items: [
      { title: "Hutchison Effect featured on Japanese TV Asahi UFO Special (1993)",
        image: "https://files.peakd.com/file/peakd-hive/mes/23xATtygCai5N7PHru9VAwE1QuA4TwpZEymHPaXWyRAJHoJn19h8jdfj2KxWhpBfNZnHm.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/fzwbhfmi"], ["3Speak", "https://3speak.tv/watch?v=mes/fzwbhfmi"], ["YouTube", "https://youtu.be/8vDV_ao6LmQ"], ["BitChute", "https://www.bitchute.com/video/9jnlTU8citpM/"], ["Odysee", "https://odysee.com/@mes:8/Hutchison-Effect-Japan-UFO-TV-1993:7"], ["Rumble", "https://rumble.com/v6y5z72-hutchison-effect-featured-on-japanese-tv-asahi-ufo-special-1993.html"], ["Summary", "https://inleo.io/threads/view/mes/re-leothreads-2aa5ywpq7"]] },
      { title: "Hutchison Effect featured on Japanese TV News (1994)",
        image: "https://files.peakd.com/file/peakd-hive/mes/23wCJNGynEWvNECQihzX8JX5bUtmJZWter8Mo9LMbf2RusyadPcVPtFnHNAQJxN5KVRFQ.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/ziububjd"], ["3Speak", "https://3speak.tv/watch?v=mes/ziububjd"], ["YouTube", "https://youtu.be/9Ky12K9jETI"], ["Telegram", "https://t.me/meslinks/31871"], ["BitChute", "https://www.bitchute.com/video/zelXNmIDj1Cj"], ["Odysee", "https://odysee.com/Hutchison-Effect-Japan-1994:b2abbebe0015caf560018b81707ef64273a9ebd8"], ["Rumble", "https://rumble.com/v6zheck-hutchison-effect-featured-on-japanese-tv-news-1994.html"], ["Summary", "https://inleo.io/threads/view/mes/re-leothreads-2nbr8qde"]] },
      { title: "BCIT Magazine Visits John Hutchison's New Westminster Apartment (2007)",
        image: "https://files.peakd.com/file/peakd-hive/mes/23tvefZmYrPzZChNWJRAmntVTURrVjNfsbF28HcwauvySUPqrShHRAo3kizXSmqshsVpH.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/vtfyegru"], ["3Speak", "https://3speak.tv/watch?v=mes/vtfyegru"], ["YouTube", "https://youtu.be/-nvVEOed2SU"], ["BitChute", "https://old.bitchute.com/video/o8jUPDot7GSx/"], ["Odysee", "https://odysee.com/@mes:8/BCIT-Magazine-Hutchison-Apartment-2007:0"], ["Rumble", "https://rumble.com/v6t53xx-bcit-magazine-visits-john-hutchisons-new-westminster-apartment-2007.html"], ["Summary", "https://inleo.io/threads/view/mes/re-leothreads-238qzfwve"]] },
      { title: "Rare Footage of the Hutchison Effect inside John's Vancouver Apartment (2007)",
        image: "https://files.peakd.com/file/peakd-hive/mes/23tmDmbgyv1LY3k8wTyjK7GrHPWrXg1qTKniFjcwRGgLDxc8Y8oYEhyFzNA7mL6EURtyC.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/yonwvsmo"], ["3Speak", "https://3speak.tv/watch?v=mes/yonwvsmo"], ["BitChute", "https://www.bitchute.com/video/Dp4w2N4gakCE"], ["Odysee", "https://odysee.com/@mes:8/Hutchison-Effect-Vancouver-2007:9"], ["Rumble", "https://rumble.com/v4qbi69-rare-footage-of-the-hutchison-effect-inside-johns-vancouver-apartment-2007.html"]] },
      { title: "Thomas Bearden explains the Hutchison Effect via Scalar Interferometry",
        image: "https://files.peakd.com/file/peakd-hive/mes/Ep5oc2Fz96HEDqCL67g6QFCAFBFWVbA8L1Qk3RazjrwYGTcbezwqktSdt2acDWZuy3Y.png",
        links: [["Hive", "https://inleo.io/@mes/amazing-1984-report-by-thomas-bearden-star-wars-now-jel"], ["3Speak", "https://3speak.tv/watch?v=mes/3speak-1780351388637"], ["YouTube", "https://youtu.be/BGoYWuo5tOU"], ["Telegram", "https://t.me/meslinks/29310"]] },
    ],
  },
  {
    id: "hutchison-unedited-footage",
    title: "Unedited Footage",
    items: [
      { title: "Unedited Hutchison Effect: 5 Hours of 1985 Footage Filmed by Jack Houck",
        image: "https://files.peakd.com/file/peakd-hive/mes/23wqbqanr7gZBSavserMjJZPWtzcPm7oeDMfasPGxmiBh5kXjwt5CDRMen4uQ9tWEHbAw.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/oqetactn"], ["3Speak", "https://3speak.tv/watch?v=mes/oqetactn"], ["YouTube", "https://youtu.be/YGBreLhxSmE"], ["BitChute", "https://old.bitchute.com/video/vCxjyeTq7aKy/"], ["Odysee", "https://odysee.com/Unedited-Hutchison-Effect-1985-Jack-Houck:ba32c47e44ea9fe718c21d2cfd17913e340b9c60"], ["Rumble", "https://rumble.com/v6rxnpn-unedited-hutchison-effect-5-hours-of-1985-footage-filmed-by-jack-houck.html"]] },
      { title: "Unedited Hutchison Effect: 2 Hours of Rare 1988 Footage",
        image: "https://files.peakd.com/file/peakd-hive/mes/23uFRQAP4eGkVCSwz6dRvHBMpy7nN6nyzo3wd9nUkfJu66i62JTDcMdKBCyXBZJS1e2nt.jpeg",
        links: [["Hive", "https://peakd.com/hive-181335/@mes/kzvdtzom"], ["3Speak", "https://3speak.tv/watch?v=mes/kzvdtzom"], ["YouTube", "https://youtu.be/KXTigZDG3cI"], ["BitChute", "https://bitchute.com/video/czQeATk2pRrz/"], ["Odysee", "https://odysee.com/Unedited-Hutchison-Effect-1988:51a537c5e56cd0b42c9f24354f03eaac36bc9897"], ["Rumble", "https://rumble.com/v69fius-unedited-hutchison-effect-2-hours-of-rare-1988-footage.html"]] },
      { title: "Unedited Hutchison Effect: 4 Hours of Rare 1989 Footage",
        image: "https://files.peakd.com/file/peakd-hive/mes/23t7azvxeVt8Mvj7nRFSTB1vE79cqmEDnyWfrva8q7swUUH9xarLvJE3wfc75feCU5wiK.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/yysmsumd"], ["3Speak", "https://3speak.tv/watch?v=mes/yysmsumd"], ["YouTube", "https://youtu.be/P-5_t_A3jnY"], ["BitChute", "https://bitchute.com/video/UbjApFbLdPDi/"], ["Odysee", "https://odysee.com/Unedited-Hutchison-Effect-1989:abaab4e798fd072ce8793344c9f94c2551512811"], ["Rumble", "https://rumble.com/v6h0ffs-unedited-hutchison-effect-4-hours-of-rare-1989-footage.html"]] },
      { title: "Unedited Hutchison Effect: 5 Hours of Rare 2006 Footage",
        image: "https://files.peakd.com/file/peakd-hive/mes/23wC5hB1xkajdvjroYPB3WULEY33NJU8uDodZgwNNrANfrkFrmcaDW5UXGf56j4yozVHR.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/nwaqszyo"], ["3Speak", "https://3speak.tv/watch?v=mes/nwaqszyo"], ["YouTube", "https://youtu.be/uEgV3587IDI"], ["BitChute", "https://bitchute.com/video/P6ob1SBuXRDu/"], ["Odysee", "https://odysee.com/@mes:8/Unedited-Hutchison-Effect-2006:7"], ["Rumble", "https://rumble.com/v60rh0k-unedited-hutchison-effect-5-hours-of-rare-2006-footage.html"]] },
      { title: "Unedited Hutchison Effect: 6 Hours of Rare 2007 Footage",
        image: "https://files.peakd.com/file/peakd-hive/mes/23xVPAAe9crRUa2hGLQbt65Qb8SCAEDAqGhYoPBgGLcQgvdtwYYEyh7CRphsBQHrQKih3.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/blmbleww"], ["3Speak", "https://3speak.tv/watch?v=mes/blmbleww"], ["YouTube", "https://youtu.be/CbiHmfWoExM"], ["BitChute", "https://bitchute.com/video/BkgRyL1zqAYX/"], ["Odysee", "https://odysee.com/@mes:8/Unedited-Hutchison-Effect-2007-Footage:b"], ["Rumble", "https://rumble.com/v62w0ih-unedited-hutchison-effect-6-hours-of-rare-2007-footage.html"]] },
    ],
  },
  {
    id: "hutchison-interviews",
    title: "Interviews and Presentations",
    items: [
      { title: "Overview of the Hutchison Effect by George Hathaway in 1993",
        image: "https://files.peakd.com/file/peakd-hive/mes/23uFRQ9rBT8SgFqiZKinXqjUi8eACNQSQopk5DCk5XjwfUShqNuZrHgHqY322g51Y1dSx.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/ikarokgh"], ["3Speak", "https://3speak.tv/watch?v=mes/ikarokgh"], ["YouTube", "https://youtu.be/tppQ1i8gkZo"], ["BitChute", "https://old.bitchute.com/video/7bJmwjkRI9Jg/"], ["Odysee", "https://odysee.com/Hutchison-Effect-George-Hathaway-1993:ccfb717bd02f8275e222b8ac2e5c7ff13133cd30"], ["Summary", "https://inleo.io/threads/view/mes/re-leothreads-fm5gwvqm"]] },
      { title: "John Hutchison Interviewed by Tom Sky in his Vancouver Lab (2007)",
        image: "https://images.3speak.tv/images/1787348035470-17ce55ab8e527dfd.webp",
        links: [["Screenshots", "https://mes.fm/hutchison-tom-sky"], ["3Speak", "https://3speak.tv/watch?v=mes/john-hutchison-interviewed-224"], ["YouTube", "https://youtu.be/eEBDSRqCkYk"], ["Telegram", "https://t.me/meslinks/35399"], ["BitChute", "https://www.bitchute.com/update_video/qv45ur4O6CGk"], ["Odysee", "https://odysee.com/@mes:8/John-Hutchison-Tom-Sky"], ["Rumble", "https://rumble.com/v7ehiuw-john-hutchison-interviewed-by-tom-sky-in-his-vancouver-lab-2007.html"]] },
      { title: "John Hutchison Interview on Journey with Brenda Roberts (1997): Crystal Energy",
        image: "https://files.peakd.com/file/peakd-hive/mes/23uFMmtFRLjwaohg4RpM84UAuvuZuGEjGjvBj2NJvkDDJjo1eU6YiKvJvc3xH4Xj1G5rc.jpeg",
        links: [["3Speak", "https://3speak.tv/watch?v=mes/8a64c253"], ["YouTube", "https://youtu.be/VPcmKJx-zBs"], ["Telegram", "https://t.me/meslinks/34025"], ["BitChute", "https://www.bitchute.com/video/HiCHEmoPD25a/"], ["Odysee", "https://odysee.com/@mes:8/John-Hutchison-Journey-Brenda-Roberts-1997-Energy:0"], ["Rumble", "https://rumble.com/v775mve-john-hutchison-interview-on-journey-with-brenda-roberts-1997-crystal-energy.html"], ["Summary", "https://inleo.io/threads/view/mes/re-leothreads-2swnudmnr"]] },
      { title: "John Hutchison Interview on Journey with Brenda Roberts (1997): The Hutchison Effect",
        image: "https://files.peakd.com/file/peakd-hive/mes/23uQjgw2MJwQvKPcy5sZGUGbF61eaGNP6V8NKRT7eYqqdxn2FxDeXUeNXFyc4DC8eQ5NA.jpeg",
        links: [["3Speak", "https://3speak.tv/watch?v=mes/dd842563"], ["YouTube", "https://youtu.be/rTTxmLyjpFQ"], ["Telegram", "https://t.me/meslinks/33992"], ["BitChute", "https://www.bitchute.com/video/iEWOOUlHunjp/"], ["Odysee", "https://odysee.com/@mes:8/John-Hutchison-Journey-Brenda-Roberts-1997:6"], ["Rumble", "https://rumble.com/v770udg-john-hutchison-interview-on-journey-with-brenda-roberts-1997-the-hutchison-.html"], ["Summary", "https://inleo.io/threads/view/mes/re-leothreads-2wlaau9mq"]] },
      { title: "MES Hanging out with John Hutchison in the Lab!",
        image: "https://files.peakd.com/file/peakd-hive/mes/23xp3xvJntnHm8hnDkvKRUHVPZLQ6MnJqe7bSY8uQk3Fc3gBM2ApR7VMhNH6AT7ewABe4.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/dywbmnes"], ["3Speak", "https://3speak.tv/watch?v=mes/dywbmnes"], ["YouTube", "https://youtu.be/CH3zDeHiswM"], ["Telegram", "https://t.me/meslinks/32679"], ["BitChute", "https://www.bitchute.com/video/EhNItFSxG5Pk"], ["Odysee", "https://odysee.com/@mes:8/MES-John-Hutchison-Lab:9"], ["Rumble", "https://rumble.com/v72nhrg-mes-hanging-out-with-john-hutchison-in-the-lab.html"], ["Summary", "https://inleo.io/threads/view/mes/re-leothreads-2cctrhdpd"]] },
      { title: "MES Livestream 120: John Hutchison and Kerry Cassidy on the Show!",
        image: "https://files.peakd.com/file/peakd-hive/mes/23tm7U9QaoFXTqwfnqtzHwJ2D1gWufgMxocGXTQm81MCXrSrdiPKpLWHNsPS6fcCZqfqF.jpeg",
        links: [["Hive", "https://3speak.tv/watch?v=mes/zqgeijqo"], ["3Speak", "https://3speak.tv/watch?v=mes/zqgeijqo"], ["YouTube", "https://youtube.com/live/Kt8XFEPC0tA"], ["Telegram", "https://t.me/meslinks/32755"], ["BitChute", "https://www.bitchute.com/video/tHlTtW40zEv2/"], ["Odysee", "https://odysee.com/@mes:8/MES-Livestream-120-John-Hutchison-Kerry-Cassidy:2"], ["Rumble", "https://rumble.com/v730vdy-mes-livestream-120-john-hutchison-and-kerry-cassidy-on-the-show.html"], ["Kerry Cassidy Show", "https://rumble.com/v72y83k-john-huthison-free-energy-portal-tech-and-time-travel.html"], ["Project Camelot article", "https://projectcamelotportal.com/2025/12/13/john-hutchison-free-energy-portal-tech-and-time-travel/"], ["X", "https://x.com/MathEasySolns/status/2000336497103220860"], ["Summary", "https://inleo.io/threads/view/mes/re-leothreads-2yxxfoerj"]] },
      { title: "John Hutchison Interview on the Elaine Smitha Show (1994): The Hutchison Effect",
        image: "https://files.peakd.com/file/peakd-hive/mes/23tbrij4LhcjoC8vZTX69q7ZidGBR1i2Nbxx1mpf2q82LNCtcjJL6VYnU65tYZrrmWr63.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/hdnytaio"], ["3Speak", "https://3speak.tv/watch?v=mes/hdnytaio"], ["YouTube", "https://youtu.be/izpD1jonySI"], ["BitChute", "https://old.bitchute.com/video/XMN76wcuH0CS/"], ["Odysee", "https://odysee.com/@mes:8/John-Hutchison-Elaine-Smitha-1994-Hutchison-Effect:2"], ["Rumble", "https://rumble.com/v6rqvdd-john-hutchison-interview-on-the-elaine-smitha-show-1994-the-hutchison-effec.html"], ["Summary", "https://inleo.io/threads/view/mes/re-leothreads-2z9zrgwej"]] },
      { title: "John Hutchison Interview on the Elaine Smitha Show (2000): Levitation",
        image: "https://files.peakd.com/file/peakd-hive/mes/23xATjo4sfsJvzMiEwYyFembNHLLfi12WkLGoovdVy16MZuQZjVaMF4q1cfqMDdLAoL9R.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/tmfowznk"], ["3Speak", "https://3speak.tv/watch?v=mes/tmfowznk"], ["YouTube", "https://youtu.be/3lriJ-i1UcU"], ["BitChute", "http://bitchute.com/video/2MRiKnexZgQS/"], ["Odysee", "https://odysee.com/John-Hutchison-Interview-Elaine-Smitha-2000-Levitation:10f3a825d23bd52300fe4fbb7a45374c0961347c"], ["Rumble", "https://rumble.com/v6eu8zs-john-hutchison-interview-on-the-elaine-smitha-show-2000-levitation.html"]] },
      { title: "John Hutchison Interview on the Elaine Smitha Show (2000): Discoveries in Zero Point Energy",
        image: "https://files.peakd.com/file/peakd-hive/mes/23uQtscz75HzYZsBhWm9C4ssAJKnaNGKNvVebGX1bxPCgctmFneFYkK6zAftUP47fU25H.JPEG",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/mywbvjww"], ["3Speak", "https://3speak.tv/watch?v=mes/mywbvjww"], ["YouTube", "https://youtu.be/H8krEbwntmc"], ["BitChute", "https://www.bitchute.com/video/pEjfJM7gR2So"], ["Odysee", "https://odysee.com/@mes:8/John-Hutchison-Interview-Elaine-Smitha-2000-ZPE:5"], ["Rumble", "https://rumble.com/v67d34s-john-hutchison-interview-on-the-elaine-smitha-show-2000-discoveries-in-zero.html"]] },
      { title: "John Hutchison Interview on the Elaine Smitha Show (2000): What's New in Free Energy?",
        image: "https://files.peakd.com/file/peakd-hive/mes/23zS5715FWbR8X6wLbSCMUzu92fZrBiKLfieMGeDfvyrdWuoZmdW1ZPB66f9H4YWEb9SU.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/wyinhvtd"], ["3Speak", "https://3speak.tv/watch?v=mes/wyinhvtd"], ["YouTube", "https://youtu.be/Xvm16xyYxrQ"], ["BitChute", "https://bitchute.com/video/4pvfdWk3NA4w/"], ["Odysee", "https://odysee.com/@mes:8/John-Hutchison-Elaine-Smitha-2000-Free-Energy:5"], ["Rumble", "https://rumble.com/v6l5sag-john-hutchison-interview-on-the-elaine-smitha-show-2000-whats-new-in-free-e.html"]] },
      { title: "John Hutchison Interview on the Elaine Smitha Show (2000): Skunk Works",
        image: "https://files.peakd.com/file/peakd-hive/mes/23x17DtHfjfNRm6hpXMAzg3Lohx1N9c6KRP9gdZubRav9uo8myRs1EgSif88M5bKr9fNG.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/dezouman"], ["3Speak", "https://3speak.tv/watch?v=mes/dezouman"], ["YouTube", "https://youtu.be/PQ9w5BxIWoA"], ["BitChute", "https://www.bitchute.com/video/OKQCJJprP91Y/"], ["Odysee", "https://odysee.com/@mes:8/John-Hutchison-Elaine-Smitha-2000-Skunk-Works:3"], ["Rumble", "https://rumble.com/v6qdxum-john-hutchison-interview-on-the-elaine-smitha-show-2000-skunk-works.html"]] },
      { title: "Jeane Manning 1996 Presentation: The Coming Energy Revolution",
        image: "https://files.peakd.com/file/peakd-hive/mes/23vi3sKhKSjErXdiDL2yukpxqnbxrUd3zbxExPpBZxfbyQwHCq7LDdca7SGBLN3xd4PJo.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/jasrjvwl"], ["3Speak", "https://3speak.tv/watch?v=mes/jasrjvwl"], ["YouTube", "https://youtu.be/i_8FKS3VC0E"], ["BitChute", "https://old.bitchute.com/video/cbl0ulz1iXGg/"], ["Odysee", "https://odysee.com/@mes:8/Jeane-Manning-1996-Energy-Revolution:0"], ["Rumble", "https://rumble.com/v6vvja7-jeane-manning-1996-presentation-the-coming-energy-revolution.html"], ["Summary", "https://inleo.io/threads/view/mes/re-leothreads-crkq7ua6"]] },
    ],
  },
  {
    id: "cold-fusion-lenr",
    title: "Cold Fusion / Low Energy Nuclear Reactions (LENR)",
    items: [
      { href: "https://www.youtube.com/playlist?list=PLai3U8-WIK0FKVpHL_onhaqBeVP-8qJXV", title: "Free Energy playlist", standalone: true },
      { title: "RARE Steven Krivit Interview with Martin Fleischmann discussing Cold Fusion (2003)",
        image: "https://files.peakd.com/file/peakd-hive/mes/23xKvVLKmjjLcTPfGnpz4auLqBhhX4EQwzC7EcUq5XBmz3Y5SE4WpMm5RGWoavY7yiB1M.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/0838bf62"], ["3Speak", "https://3speak.tv/watch?v=mes/0838bf62"], ["YouTube", "https://youtu.be/kMnY9TX06kw"], ["Telegram", "https://t.me/meslinks/34417"], ["BitChute", "https://www.bitchute.com/video/4oHDcWTjL8yr/"], ["Odysee", "https://odysee.com/@mes:8/Martin-Fleischmann-Steven-Krivit-2003:b"], ["Rumble", "https://rumble.com/v78qu6m-rare-steven-krivit-interview-with-martin-fleischmann-discussing-cold-fusion.html"], ["Summary", "https://inleo.io/threads/view/mes/re-leothreads-xvinzwe"]] },
      { title: "Martin Fleischmann Recounts the 1985 \"Hole in the Floor\" Palladium Electrolysis Experiment",
        image: "https://files.peakd.com/file/peakd-hive/mes/23y9AsJGvSeFwcyfCvm96ChMNfETJAVrfifK1n5BXTCQijLFi7HrtZJ4vFyfLkxNkNGWm.jpeg",
        links: [["Screenshots", "https://peakd.com/hive-128780/@mes/31739ef7"], ["3Speak", "https://3speak.tv/watch?v=mes/31739ef7"], ["YouTube", "https://youtu.be/VaWSwxzCyCg"], ["Telegram", "https://t.me/meslinks/34559"], ["BitChute", "https://www.bitchute.com/video/vwRVnzyObLdv/"], ["Odysee", "https://odysee.com/Martin-Fleischmann-1985-Hole-Floor-Palladium-Electrolysis:874dff2e462b7d6d5de34860f984c2cc99d62e7b"], ["Rumble", "https://rumble.com/v797vl2-martin-fleischmann-recounts-the-1985-hole-in-the-floor-palladium-electrolys.html"], ["Summary", "https://inleo.io/threads/view/mes/re-leothreads-ihyg2xjk"]] },
    ],
  },
  {
    id: "hutchison-livestreams",
    title: "MES Livestreams",
    items: [
      { title: "MES Livestream 118: Hutchison Effect Zero Point Harmonics",
        image: "https://files.peakd.com/file/peakd-hive/mes/23wC5Fdv3oj2nmTFSFCxRo9QnUsZv3qtcsaYvHSdd9pXn8V3EvdtDdPbiyWn2ejWTYH2Y.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/odmoypqh"], ["YouTube", "https://youtube.com/live/Elux1MyqJzo"], ["Summary", "https://inleo.io/threads/view/mes/re-leothreads-ma71wv1s"]] },
      { title: "MES Livestream 115: John Hutchison Joins the Show Again!",
        image: "https://files.peakd.com/file/peakd-hive/mes/23z7N18ufyj8prPjVNSJg1UcfDT7bQCnrexxKjNUXVHHTMfgjm29Vt55Jq5h29etRkbmR.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/livestream-115-john-hutchison-7fp"], ["YouTube", "https://youtube.com/live/Jn38lxj3ebU"], ["BitChute", "https://www.bitchute.com/video/x1ZPf5Gpp3Y8"], ["Odysee", "https://odysee.com/MES-Livestream-115-John-Hutchison:e9351e4a758b2d5b679d58b718963455927882c9"], ["Rumble", "https://rumble.com/v7138mq-mes-livestream-115-john-hutchison-joins-the-show-again.html"], ["X", "https://x.com/i/broadcasts/1YqKDNjZrNNJV"], ["Notes", "https://peakd.com/hive-128780/@mes/livestream-115-john-hutchison-7fp"], ["Trailer", "https://youtu.be/o90ylugSL_M"]] },
      { title: "MES Livestream 102: Eddie Kuberski, Carmen Miller, and John Hutchison Join the Show!",
        image: "https://files.peakd.com/file/peakd-hive/mes/23vsQY66pj5pjkRbsUMq5AjvsARGoKwQvSfPrhZk6rADVM8s61GTTWNtd2ds2518DPyTK.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/livestream-102-kuberski-miller-hutchison-l7w"], ["YouTube", "https://youtube.com/live/gBXCVIC3AGQ"], ["BitChute", "https://www.bitchute.com/video/b7FMKsSPHGN7"], ["Odysee", "https://odysee.com/@mes:8/MES-Livestream-102-Kuberski-Miller-Hutchison:b"], ["Rumble", "https://rumble.com/v6xd1bg-mes-livestream-102-eddie-kuberski-carmen-miller-and-john-hutchison-join-the.html"], ["X", "https://x.com/i/broadcasts/1BdGYqZoaeBGX"], ["Summary", "https://inleo.io/threads/view/mes/re-leothreads-2hzr6da7w"]] },
      { title: "MES Livestream 100: Paul Stoichevski and John Hutchison Join the Show!",
        image: "https://files.peakd.com/file/peakd-hive/mes/23vhwxccJLjgDb8WtLnpiRTiJXCZdVpk8K9mSskm9rUT6KtLr779d9uat2zJehapLhgDb.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/livestream-100-stoichevski-hutchison-exm"], ["YouTube", "https://youtube.com/live/HKH91H2oP88"], ["BitChute", "https://www.bitchute.com/video/YOl1HjVH3IQl"], ["Odysee", "https://odysee.com/@mes:8/MES-Livestream-100-Stoichevski-Hutchison:d"], ["Rumble", "https://rumble.com/v6wptlw-mes-livestream-100-paul-stoichevski-and-john-hutchison-join-the-show.html"], ["X", "https://x.com/i/broadcasts/1eaJbWadmXQxX"], ["Trailer", "https://youtu.be/8dL7KQUEeOI"], ["Summary", "https://inleo.io/threads/view/mes/re-leothreads-sebn3xkt"]] },
      { title: "MES Livestream 97: Jeane Manning and John Hutchison Join the Show!",
        image: "https://files.peakd.com/file/peakd-hive/mes/23uQrDEJGrTAdc4yK6GPedULYPMnR4cF5zBzMmMaGNnZbnrh8SAXDfWtra96sK5dzX3Pr.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/livestream-97-jeane-manning-john-hutchison-8rr"], ["YouTube", "https://youtube.com/live/-jH3bghGBZ4"], ["BitChute", "https://www.bitchute.com/video/G1thPRejEUhs"], ["Odysee", "https://odysee.com/MES-Livestream-97-Jeane-Manning-John-Hutchison:a010f9c4f5061a6a24b50c4b31235fa145cfc7bb"], ["Rumble", "https://rumble.com/v6vrf0t-mes-livestream-97-jeane-manning-and-john-hutchison-join-the-show.html"], ["X", "https://x.com/i/broadcasts/1DXxyqRPLWVxM"], ["Trailer", "https://youtu.be/O-KoQ3_Drag"], ["Summary", "https://inleo.io/threads/view/mes/re-leothreads-21lqcpdq4"]] },
      { title: "MES Livestream 83: John Hutchison and Paul Mueller Discuss Experimental Science",
        image: "https://files.peakd.com/file/peakd-hive/mes/23xAdqb6tDkF8CXKPxi7ZLHzfikqrut5yzGAg5WdJ557LmzZ35soCaBriRjFi7cbz21x7.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/livestream-83-hutchison-inventor3-383e"], ["YouTube", "https://youtube.com/live/Ic_LJPmJLgs"], ["Odysee", "https://odysee.com/MES-Livestream-83-Hutchison-Inventor3:fb17fda3d0b6cbf10ecb6bfbb07a98a9cd608878"], ["Trailer", "https://youtu.be/0xyH_TMubqI"], ["Summary", "https://inleo.io/threads/view/mes/re-leothreads-33kbyncej"]] },
      { title: "MES Livestream 76: John Hutchison Discusses Hutchison Effect Replication",
        image: "https://files.peakd.com/file/peakd-hive/mes/23vi1YoCB55gE6FjakGFyB7a2T14gJHpxjNBUV2fNDKjtsPWBt7VtM6hnnqevK1jjrr8u.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/livestream-76-john-hutchison-replication-4oh"], ["BitChute", "https://www.bitchute.com/video/xZ8uHjOQd0vM"], ["Odysee", "https://odysee.com/MES-Livestream-76-John-Hutchison-Replication:964bdf6a506a3d0acf644d7ba84c34a59dec69ef"], ["Rumble", "https://rumble.com/v6kzsu7-mes-livestream-76-john-hutchison-discusses-hutchison-effect-replication.html"], ["Summary", "https://inleo.io/threads/view/mes/re-mes-sru6dd"]] },
      { title: "MES Livestream 66: Never Before Seen Hutchison Effect Footage",
        image: "https://files.peakd.com/file/peakd-hive/mes/23xyV9Hor2t4ePKj52tdRRYfVJ16hPEU2dtTWBfL8qyjWqD2gS6QL6NvPwh8PK2VpYHWA.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/ivestream-66-rare-hutchison-effect-footage"], ["YouTube", "https://youtube.com/live/PFKteWK2H5I"], ["Odysee", "https://odysee.com/MES-Livestream-66-Rare-Hutchison-Effect-Footage:4bdee40ad91af371dafc365b897fa58e6cdfc662"], ["Rumble", "https://rumble.com/v5witow-mes-livestream-66-never-before-seen-hutchison-effect-footage.html"], ["Trailer", "https://youtu.be/WbvO8BbKIP0"], ["Summary", "https://inleo.io/threads/view/mes/re-mes-2yabgvh9a"]] },
      { title: "MES Livestream 63: Tour of John Hutchison's Lab",
        image: "https://files.peakd.com/file/peakd-hive/mes/23xKvA2EGsAom9jmYdH2nL8Cwh5Sr5QRZm1ESviqN41LaK59nUnY6jaMp7ciHvYJd5Gs1.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/fsjbtemx"], ["YouTube", "https://youtube.com/live/mP5DLMH54LM"], ["Summary", "https://inleo.io/threads/view/mes/re-mes-2xm8eper2"]] },
      { title: "MES Livestream 62: Nancy and John Hutchison Frequency Cannabis",
        image: "https://files.peakd.com/file/peakd-hive/mes/23vi8AU4pN5yMg6woLKPAoQRQhFy2htg2EGiMmZQzeFcDcZ2WDuAhqGjkqvhTyizJzmPt.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/livestream-62-hutchison-harmonics"], ["YouTube", "https://youtube.com/live/2_qOG4KDfE8"], ["Odysee", "https://odysee.com/MES-Livestream-62-Hutchison-Harmonics:87a790fac4202a031a291244654e54bcf7d1019c"], ["Rumble", "https://rumble.com/v5p11mb-mes-livestream-62-nancy-and-john-hutchison-frequency-cannabis.html"], ["Trailer", "https://youtu.be/rUV2rhPhjcg"], ["Summary", "https://inleo.io/threads/view/mes/re-mes-udwbykry"]] },
      { title: "MES Livestream 40: John Hutchison Joins the Show!",
        image: "https://files.peakd.com/file/peakd-hive/mes/23vsFeLaUQbZrQWSwpZ6v4XEqHDgoMfyKNroH4kF6QwVk8zdL41ZTA9vAxiimoo2ameTz.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/livestream-40-john-hutchison"], ["YouTube", "https://youtube.com/live/f5GJiAUhr9c"], ["Summary", "https://inleo.io/threads/view/mes/re-mes-36sucyha8"]] },
      { title: "MES Livestream 37: The Hutchison Effect is Real (Debunking the \"Debunkers\")",
        image: "https://files.peakd.com/file/peakd-hive/mes/23wCBnShS1n3PurdLXVAWeqtBYCPVnkHPVvZYH7LnWuM4gQLgpDCgiMtdkjmPJGt9xFPx.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/livestream-37-hutchison-effect"], ["YouTube", "https://youtube.com/live/EOfO1VcGXCA"], ["Summary", "https://inleo.io/threads/view/mes/re-mes-dg6cn4fb"]] },
      { title: "MES Livestream 20: Hutchison Effect Deep Dive",
        image: "https://files.peakd.com/file/peakd-hive/mes/23ywnoW9bh8WHa8cMpr89CkdVfs2JcLxCJrZ46DH7cC5xHDERRsrfakVCngCfuimW2Mp4.jpeg",
        links: [["Hive", "https://peakd.com/hive-128780/@mes/livestream-20-hutchison-effect"], ["YouTube", "https://youtube.com/live/FHU3nq8oL04"], ["Summary", "https://inleo.io/threads/view/mes/re-mes-2kwjhdig6"]] },
    ],
  },
];
