/* Search box + category chips for the card hub pages (mes.fm/calculators, mes.fm/tools).
   Markup (generated by organize_hub_cards.py):
     <div class="hub-filter"> <input id="hub-search"> <div class="hub-chips" id="hub-chips"><button data-c="all|<cat>">..</button>.. </div> </div>
     <section class="hub-cat" data-cat="<cat>"><h2 class="hub-cat__title">..</h2><table class="tbl tbl--stack">..td.calc-container..</table></section> ..
     <p id="hub-empty" hidden>..</p>
   Typing filters cards by title + description (every word must match); a chip limits to one category; sections with no
   visible card are hidden. #<cat> in the URL preselects a chip. Self-contained: injects its own CSS (incl. dark mode). */
(function () {
    "use strict";
    var input = document.getElementById("hub-search"), chips = document.getElementById("hub-chips");
    if (!input || !chips) return;
    var cards = Array.prototype.slice.call(document.querySelectorAll(".hub-cat td.calc-container"));
    var sections = Array.prototype.slice.call(document.querySelectorAll(".hub-cat"));
    var empty = document.getElementById("hub-empty");

    var css = document.createElement("style");
    css.textContent =
        ".hub-filter{margin:0 0 1.2em}" +
        ".hub-filter input{display:block;width:100%;box-sizing:border-box;font:inherit;font-size:1.05em;padding:.65em .8em;border:1px solid #b9c1cc;border-radius:.4em;background:#fff;color:#222}" +
        ".hub-filter input:focus{outline:none;border-color:#277bb6;box-shadow:0 0 0 2px rgba(39,123,182,.22)}" +
        ".hub-chips{display:flex;flex-wrap:wrap;gap:.45em;margin-top:.7em}" +
        ".hub-chips button{font:inherit;font-size:.85em;cursor:pointer;padding:.4em .9em;border-radius:1.2em;border:1px solid #c3c9d2;background:#fff;color:#444}" +
        ".hub-chips button:hover{border-color:#277bb6;color:#277bb6}" +
        ".hub-chips button[aria-pressed=true]{background:#277bb6;border-color:#277bb6;color:#fff}" +
        ".hub-cat{margin:0 0 1.6em}" +
        ".hub-cat__title{font-size:1.15em;font-weight:700;margin:0 0 .6em;padding-bottom:.3em;border-bottom:2px solid #dbe9f8;color:#1e2733}" +
        ".hub-cat__count{font-size:.75em;font-weight:400;color:#8a93a0;margin-left:.4em}" +
        ".hub-cat[hidden],.hub-cat td[hidden],#hub-empty[hidden]{display:none !important}" +
        "#hub-empty{color:#6a7280;font-style:italic;padding:1em 0}" +
        "body.dark-mode .hub-filter input{background:#2a2a2a;color:#eee;border-color:#555}" +
        "body.dark-mode .hub-chips button{background:#2a2a2a;color:#ddd;border-color:#555}" +
        "body.dark-mode .hub-chips button[aria-pressed=true]{background:#6cb6f5;border-color:#6cb6f5;color:#111}" +
        "body.dark-mode .hub-cat__title{color:#eee;border-color:#3a4a5a}body.dark-mode #hub-empty{color:#aaa}";
    document.head.appendChild(css);

    var cat = "all";
    function textOf(td) { return (td.textContent || "").toLowerCase().replace(/\s+/g, " "); }
    var texts = cards.map(textOf);

    function apply() {
        var words = input.value.toLowerCase().trim().split(/\s+/).filter(Boolean), any = false;
        cards.forEach(function (td, i) {
            var sec = td.closest(".hub-cat");
            var ok = (cat === "all" || sec.getAttribute("data-cat") === cat) && words.every(function (w) { return texts[i].indexOf(w) !== -1; });
            td.hidden = !ok;
            if (ok) any = true;
        });
        sections.forEach(function (s) {
            var visible = Array.prototype.some.call(s.querySelectorAll("td.calc-container"), function (td) { return !td.hidden; });
            s.hidden = !visible;
        });
        if (empty) empty.hidden = any;
    }
    function setCat(c) {
        cat = c;
        Array.prototype.forEach.call(chips.querySelectorAll("button"), function (b) { b.setAttribute("aria-pressed", b.getAttribute("data-c") === c ? "true" : "false"); });
        apply();
    }
    input.addEventListener("input", apply);
    chips.addEventListener("click", function (e) { var b = e.target.closest("button"); if (b) setCat(b.getAttribute("data-c")); });
    input.addEventListener("keydown", function (e) { if (e.key === "Escape") { input.value = ""; setCat("all"); } });
    var h = (location.hash || "").slice(1);
    if (h && chips.querySelector('button[data-c="' + h + '"]')) setCat(h);
    else apply();
})();
