// Content for mes.fm/pg ("PizzaGate Video Series") and its Video Series page mes.fm/pg-series. Hand-maintained; read by build.mjs.
//
// The 32 parts were converted (2026-10-08) from https://peakd.com/pg/@mes/videos, newest first: Part 32 is the first card. Add a new part at the TOP of
// the list. Item shape: { title, image, links: [[label, href], ...] }; the card goes to its first mes.fm link, else the Hive notes (peakd), else the
// first link. (Part 14's YouTube / DTube links are identical to Part 13's in the Hive post; copied as they are.)

export const SECTIONS = [
  {
    id: "pg-series",
    title: "Video Series",
    standalone: [
      { href: "/pg-bitchute", title: "BitChute playlist", icon: "&#127916;" },
      { href: "https://odysee.com/$/playlist/d93456222ba64e13c31ec872f15a1e43da4d6bee", title: "Odysee playlist", icon: "&#127916;" },
      { href: "https://peakd.com/pg/@mes/videos", title: "Hive links and notes", icon: "&#128221;" },
    ],
    items: [
  { title: "#PizzaGate Part 32: MES vs. Reddit Saga + Tamera Luzzatto Rabbit Hole + Comet Ping Pong Hacker", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/0lKfMjo6-PizzaGate20Part203220Reddit20Saga20and20Luzzatto.jpeg", links: [["Notes", "https://peakd.com/@mes/pizzagate-part-32-mes-vs-reddit-saga-tamera-luzzatto-rabbit-hole-comet-ping-pong-hacker"], ["3Speak", "https://3speak.tv/watch?v=mes/ygtxlvnq"], ["Odysee", "https://odysee.com/@mes:8/PizzaGate-Part-32-Tamera-Luzzatto-Comet-Ping-Pong:7"], ["BitChute", "https://www.bitchute.com/video/CTevjtDlQXXD/"], ["DTube", "https://d.tube/#!/v/mes/55gkecf1"], ["YouTube (deleted)", "https://youtu.be/2ZJSD64SG4I"]] },
  { title: "#PizzaGate Part 31: Hollywood Victims Speak Out! #PedoWood + Weinstein + Mind Control", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/r9QcV1Wa-PizzaGate20Part2031.jpeg", links: [["Notes", "https://peakd.com/pizzagate/@mes/pizzagate-part-31-hollywood-victims-speak-out-pedowood-weinstein-mind-control"], ["3Speak", "https://3speak.co/watch?v=mes/jzadfijk"], ["Odysee", "https://odysee.com/@mes:8/PizzaGate-Part-31-Hollywood-Victims-Speak-Out:7"], ["BitChute", "https://www.bitchute.com/video/d8tgozSLgNyh/"], ["YouTube (deleted)", "https://youtu.be/FpEyRLB_aQU"]] },
  { title: "#PizzaGate Part 30: Madeleine McCann Case Goes Right to the Top! + Halligan PsyOp + Podesta Efits", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/I2T4ALdY-PizzaGate20Part203020Madeleine20Case20Reaches20the20Top.jpeg", links: [["Notes", "https://peakd.com/pizzagate/@mes/video-notes-pizzagate-part-30-madeleine-mccann-case-goes-right-to-the-top-halligan-psyop-podesta-efits"], ["3Speak", "https://3speak.tv/watch?v=mes/vckkwztk"], ["BitChute", "https://www.bitchute.com/video/oRaarht4EWhU/"], ["DTube", "https://d.tube/#!/v/mes/m4f7qbx2"], ["YouTube (deleted)", "https://youtu.be/wrL08JgvD7U"]] },
  { title: "#PizzaGate Part 29: Pool Entertainment Luzzatto Email + WikiLeaks + 9/11 + MORE", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/Zhg5MYPI-PizzaGate20Part202920Luzzatto20Pool20Entertainment.jpeg", links: [["Notes", "https://peakd.com/pizzagate/@mes/video-notes-pizzagate-part-29-pool-entertainment-luzzatto-email-wikileaks-9-11-more"], ["3Speak", "https://3speak.tv/watch?v=mes/zrkvhcxx"], ["BitChute", "https://www.bitchute.com/video/P3NVjzoZs7Gi/"], ["DTube", "https://d.tube/v/mes/xf01f71f"], ["YouTube (deleted)", "https://youtu.be/MQlaaylj3lM"]] },
  { title: "#PizzaGate Part 28: David Brock Blackmail Scandal + Baphomet, United Nations, #ElsaGate + MORE", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/xYedwdiN-PizzaGate20Part202820David20Brock20Blackmail.jpeg", links: [["Notes", "https://peakd.com/pizzagate/@mes/video-notes-pizzagate-part-28-david-brock-blackmail-scandal-baphomet-united-nations-elsagate-more"], ["3Speak", "https://3speak.tv/watch?v=mes/yoizmknu"], ["BitChute", "https://www.bitchute.com/video/rcd5tfkewINv/"], ["DTube", "https://d.tube/#!/v/mes/r2lxfvlp"], ["YouTube (deleted)", "https://youtu.be/RsNk52IWKDA"]] },
  { title: "#PizzaGate Part 27: Was #SpiritCooking Too Much For Kanye West? + Marina Abramovic + Katy Perry", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/koajTYIY-PizzaGate20Part202720Kanye20Katy20Perry20Spirit20Cooking.jpeg", links: [["Notes", "https://peakd.com/pizzagate/@mes/video-notes-pizzagate-part-27-was-spiritcooking-too-much-for-kanye-west-marina-abramovic-katy-perry"], ["3Speak", "https://3speak.tv/watch?v=mes/jgmupgct"], ["BitChute", "https://www.bitchute.com/video/NGRLFaUuvJuX"], ["DTube", "https://d.tube/#!/v/mes/cmoh4nal"], ["YouTube (deleted)", "https://youtu.be/GPj5hgkLeb0"]] },
  { title: "#PizzaGate Part 26: Is David Brock Controlled by Hillary Clinton?", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/IOOaxpOx-PizzaGate20Part202620David20Brock20Overview.jpeg", links: [["Notes", "https://peakd.com/pizzagate/@mes/video-notes-pizzagate-part-26-is-david-brock-controlled-by-hillary-clinton-david-seaman-contest"], ["3Speak", "https://3speak.tv/watch?v=mes/gjcsicct"], ["BitChute", "https://www.bitchute.com/video/ZP649m0I1qrc"], ["DTube", "https://d.tube/#!/v/mes/9hku5vrh"], ["YouTube (deleted)", "https://youtu.be/1xEsnuhFhWs"]] },
  { title: "#PizzaGate Part 25: Madeleine McCann Case: Twitter ‘Troll’ Brenda Leyland PsyOp?!", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/PpYj2EoO-PizzaGate20Part202520Brenda20Leyland20Death.jpeg", links: [["Notes", "https://peakd.com/pizzagate/@mes/video-notes-pizzagate-part-25-madeleine-mccann-case-twitter-troll-brenda-leyland-psyop-seth-rich-shawn-lucas"], ["3Speak", "https://3speak.tv/watch?v=mes/qhwlhpsq"], ["BitChute", "https://www.bitchute.com/video/FqBSQMpc5s0o"], ["DTube", "https://d.tube/#!/v/mes/umw5p4jv"], ["YouTube (deleted)", "https://youtu.be/b2mKpQ3hoDI"]] },
  { title: "#PizzaGate Part 24: Misleading ‘PizzaGate’ vs. ‘Fake News’ Google Search Trends + Gematria + James Comey + Antifa", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/QnGXT21e-PizzaGate20Part2024.jpeg", links: [["Notes", "https://peakd.com/pizzagate/@mes/video-notes-pizzagate-part-24-misleading-pizzagate-google-search-trends-gematria-james-comey-antifa"], ["3Speak", "https://3speak.tv/watch?v=mes/tfsiuuvq"], ["Odysee", "https://odysee.com/@mes:8/pizzagate-part-24-misleading-pizzagate:e?lid=d93456222ba64e13c31ec872f15a1e43da4d6bee"], ["BitChute", "https://www.bitchute.com/video/q7Xl8EBohXjo/"], ["DTube", "https://d.tube/#!/v/mes/l11t7zg9"], ["YouTube (deleted)", "https://youtu.be/6Allk6WGWZ4"]] },
  { title: "#PizzaGate Part 23: Pedophilia Activism & Normalization + Ronald Bernard + Macron + Bill Nye + MORE", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/dCrIBgpC-PizzaGate20Part2023.jpeg", links: [["Notes", "https://peakd.com/pizzagate/@mes/video-notes-pizzagate-part-23-pedophilia-activism-and-normalization-ronald-bernard-macron-bill-nye-more"], ["3Speak", "https://3speak.tv/watch?v=mes/awbcjriv"], ["BitChute", "https://www.bitchute.com/video/wiAzk6BlRiIc"], ["DTube", "https://d.tube/#!/v/mes/f7jjbmao"]] },
  { title: "#PizzaGate Part 22: CLogo Origins + Google Censorship + Haiti UN Trafficking + MORE Censorship", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/QlVscZyM-PizzaGate20Part2022.jpeg", links: [["Notes", "https://peakd.com/pizzagate/@mes/video-notes-pizzagate-part-22-clogo-origins-google-censorship-haiti-un-trafficking-more-censorship"], ["3Speak", "https://3speak.tv/watch?v=mes/zbsnuoby"], ["BitChute", "https://www.bitchute.com/video/xjMTefiRSkzH/"], ["DTube", "https://d.tube/#!/v/mes/8o8n50ch"]] },
  { title: "#PizzaGate Part 21: GLogo Origins + YouTube Censorship + Craig Sawyer + April 7th NYC Protest", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/fnWzXvhG-PizzaGate20Part2021.jpeg", links: [["Notes", "https://peakd.com/pizzagate/@mes/video-notes-pizzagate-part-21-glogo-origins-youtube-censorship-craig-sawyer-april-7th-nyc-protest"], ["3Speak", "https://3speak.tv/watch?v=mes/zxhytrmm"], ["BitChute", "https://www.bitchute.com/video/auujv2FWYWAs"], ["DTube", "https://d.tube/#!/v/mes/x7sgedf9"], ["YouTube", "https://youtu.be/lnxUbkHEETw"]] },
  { title: "#PizzaGate Part 20: BLogo & LBLogo Origins + Alex Jones Apology + Dr. Phil Red Pill + Trudeau Foundation + MORE", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/EzLY2qyT-PizzaGate20Part2020.jpeg", links: [["Notes", "https://peakd.com/pizzagate/@mes/video-notes-pizzagate-part-20-blogo-and-lblogo-origins-alex-jones-apology-dr-phil-red-pill-trudeau-foundation-more"], ["BitChute", "https://www.bitchute.com/video/gK2tHgDkJ6YG/"], ["DTube", "https://d.tube/#!/v/mes/9tfju62n"], ["YouTube", "https://youtu.be/T1jSKzfEDNI"]] },
  { title: "#PizzaGate Part 19: Memetics / Meme Warfare + March 25th Washington DC Protest", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/23w2oL6ZHktymu11BKjLxTqV4mztiuTY4NJFztc8WaNvVsdfXYhu9YThoYg7vY557mjAu.jpg", links: [["Notes", "https://peakd.com/pizzagate/@mes/video-notes-pizzagate-part-19-memetics-meme-warfare-march-25th-washington-dc-protest"], ["BitChute", "https://www.bitchute.com/video/byxpx9D4svSu/"], ["DTube", "https://d.tube/#!/v/mes/1x5vyw5w"], ["YouTube (deleted)", "https://youtu.be/EiNKFJ2mJQM"]] },
  { title: "#PizzaGate Part 18: #Vault7 #YearZero & Pedophile Blackmail & Ken Livingstone", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/23v4fqwBUV5infnVzpveSTyWX4Fh7JgGCijiMVzUfnAP967bLkhdsvSpktgtoT7gz9AGA.jpeg", links: [["Notes", "https://peakd.com/pizzagate/@mes/video-notes-pizzagate-part-18-vault-7-year-zero-and-pedophile-blackmail-and-ken-livingstone"], ["3Speak", "https://3speak.tv/watch?v=mes/agpjodfj"], ["Odysee", "https://odysee.com/@mes:8/pizzagate-part-18-vault7-yearzero:1"], ["BitChute", "https://www.bitchute.com/video/xcUfPDHFy1op/"], ["YouTube (deleted)", "https://youtu.be/MxQ2Av9NWSI"]] },
  { title: "#PizzaGate Part 17: Kurt Eichenwald vs. Bill Moran + Google Censorship + Cernovich / Epstein Lawsuit + NCMEC + MORE", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/suPXRH3P-PizzaGate20Part2017.jpeg", links: [["Notes", "https://peakd.com/pizzagate/@mes/video-notes-pizzagate-part-17-kurt-eichenwald-vs-bill-moran-google-censorship-cernovich-epstein-lawsuit-ncmec-more"], ["BitChute", "https://www.bitchute.com/video/7ajV3ULgToo5/"], ["DTube", "https://d.tube/#!/v/mes/qcu6depg"], ["YouTube (deleted)", "https://youtu.be/7cVlEU_ZqFA"]] },
  { title: "#PizzaGate Part 16: Alex Jones vs. Bill Clinton", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/2gCi2oXs-PizzaGate20Part2016.jpeg", links: [["Notes", "https://peakd.com/pizzagate/@mes/video-notes-pizzagate-part-16-alex-jones-vs-bill-clinton"], ["BitChute", "https://www.bitchute.com/video/S5VLDQNYdpSg/"], ["DTube", "https://d.tube/#!/v/mes/jf9jgi2f"], ["YouTube (deleted)", "https://youtu.be/3uNI42WBz2Q"]] },
  { title: "#PizzaGate Part 15: Kurt Eichenwald and Justin Berry + Censorship + #CNNLeaks + MORE", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/MrElehIZ-PizzaGate20Part2015.jpeg", links: [["Notes", "https://peakd.com/pizzagate/@mes/video-notes-pizzagate-part-15-kurt-eichenwald-and-justin-berry-censorship-cnnleaks-more"], ["BitChute", "https://www.bitchute.com/video/gzN1DesInwW7/"], ["DTube", "https://d.tube/#!/v/mes/p96tfu0e"], ["YouTube (deleted)", "https://youtu.be/pcyvthBKAfM"]] },
  { title: "#PizzaGate Part 14: NY Times 2005 Pedophilia Investigation: Justin Berry + Milo + Ted Heath + MORE", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/dDclEqjD-PizzaGate20Part2014.jpeg", links: [["Notes", "https://peakd.com/pizzagate/@mes/video-notes-pizzagate-part-14-ny-times-2005-pedophilia-investigation-justin-berry-milo-ted-heath-more"], ["BitChute", "https://www.bitchute.com/video/xX2tUssxvjYl/"], ["DTube", "https://d.tube/#!/v/mes/ng0tnswh"], ["YouTube (deleted)", "https://youtu.be/r0gDGMnkyZg"]] },
  { title: "#PizzaGate Part 13: NY Times 2005 Pedophilia Investigation + Catherine Agnew + MORE", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/usiMSNhC-PizzaGate20Part2013.jpeg", links: [["Notes", "https://peakd.com/pizzagate/@mes/pizzagate-part-13-ny-times-2005-pedophilia-investigation-catherine-agnew-more"], ["BitChute", "https://www.bitchute.com/video/FvFjdchAJlBi/"], ["DTube", "https://d.tube/#!/v/mes/ng0tnswh"], ["YouTube (deleted)", "https://youtu.be/r0gDGMnkyZg"]] },
  { title: "#PizzaGate Part 12: FBI Pedophile Logos and Symbols", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/vvuapza2-PizzaGate20Part2012.jpeg", links: [["Notes", "https://peakd.com/pizzagate/@mes/video-notes-pizzagate-part-12-fbi-pedophile-logos-and-symbols"], ["BitChute", "https://www.bitchute.com/video/BG2Ie09vOHKW/"], ["DTube", "https://d.tube/#!/v/mes/s3rvajzl"], ["YouTube (deleted)", "https://youtu.be/bANFRekPNqk"]] },
  { title: "#PizzaGate Part 11: \"Fake News\", Search Trends, Jeff Sessions, #NationalPizzaDay, and MORE", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/t2vkI3jX-PizzaGate20Part2011.jpeg", links: [["Notes", "https://peakd.com/pizzagate/@mes/video-notes-pizzagate-part-11-fake-news-search-trends-jeff-sessions-nationalpizzaday-and-more"], ["BitChute", "https://www.bitchute.com/video/CBdntgCsT4ca/"], ["DTube", "https://d.tube/#!/v/mes/quegne25"], ["YouTube (deleted)", "https://youtu.be/TxB8pVmzVY0"]] },
  { title: "#PizzaGate Part 10: Kate McCann's Bizarre Book \"Madeleine\"", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/94uu9sky-PizzaGate20Part2010.jpeg", links: [["Notes", "https://peakd.com/pizzagate/@mes/video-notes-pizzagate-part-10-kate-mccann-s-bizarre-book-madeleine"], ["BitChute", "https://www.bitchute.com/video/231D7V1VXuuW/"], ["DTube", "https://d.tube/#!/v/mes/clr65yw1"], ["YouTube (deleted)", "https://youtu.be/y_f3Rmibe1k"]] },
  { title: "#PizzaGate Part 9: McCann Case: What Did Clement Freud Know About Madeleine?", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/uglj1wlL-PizzaGate20Part209.jpeg", links: [["Notes", "https://peakd.com/pizzagate/@mes/video-notes-pizzagate-part-9-mccann-case-what-did-clement-freud-know-about-madeleine"], ["BitChute", "https://www.bitchute.com/video/uspszzr49emJ/"], ["DTube", "https://d.tube/#!/v/mes/dltisuer"], ["YouTube (deleted)", "https://youtu.be/PfwJUzUYHfk"]] },
  { title: "#PizzaGate Part 8: Madeleine McCann Case: Clement Freud", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/evBTgLbR-PizzaGate20Part208.jpeg", links: [["Notes", "https://peakd.com/pizzagate/@mes/video-notes-pizzagate-part-8-mccann-case-clement-freud"], ["BitChute", "https://www.bitchute.com/video/tWg42VF7QoO6/"], ["DTube", "https://d.tube/#!/v/mes/d93pkoc9"], ["YouTube (deleted)", "https://youtu.be/tVfJCs3m3bw"]] },
  { title: "#PizzaGate Part 7: McCann / Podesta / Conspiracy Theories ADVICE", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/lKG8zQro-PizzaGate20Part207.jpeg", links: [["Notes", "https://peakd.com/pizzagate/@mes/video-notes-pizzagate-part-7-mccann-podesta-conspiracy-theories-advice"], ["BitChute", "https://www.bitchute.com/video/d9fdPWHb6iyF/"], ["DTube", "https://d.tube/#!/v/mes/9hbe2yxu"], ["YouTube (deleted)", "https://youtu.be/GdNLuXMer8Y"]] },
  { title: "#PizzaGate Part 6: McCann Case: Yvonne Martin Statements", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/LcMczKGU-PizzaGate20Part206.jpeg", links: [["Notes", "https://peakd.com/pizzagate/@mes/video-notes-pizzagate-part-6-mccann-case-yvonne-martin-statements"], ["BitChute", "https://www.bitchute.com/video/5jx95JR5gfKK/"], ["DTube", "https://d.tube/#!/v/mes/8jhgv2np"], ["YouTube (deleted)", "https://youtu.be/Vgv5WYb0PbU"]] },
  { title: "#PizzaGate Part 5: McCann Case: Gaspar Statements", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/vBNuuwKy-PizzaGate20Part205.jpeg", links: [["Notes", "https://peakd.com/pizzagate/@mes/video-notes-pizzagate-part-5-mccann-case-gaspar-statements"], ["BitChute", "https://www.bitchute.com/video/ijxuo0Xq7v6G/"], ["DTube", "https://d.tube/#!/v/mes/cvczt2yx"], ["YouTube (deleted)", "https://youtu.be/rGtb72KFFm0"]] },
  { title: "#PizzaGate Part 4: McCann / Podesta Connection (Debunking Snopes and New York Times)", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/bjcOJK7V-PizzaGate20Part204.jpeg", links: [["Notes", "https://peakd.com/pizzagate/@mes/video-notes-pizzagate-part-4-mccann-podesta-connection-debunking-snopes-and-new-york-times"], ["BitChute", "https://www.bitchute.com/video/PlP6WxnELoSg"], ["DTube", "https://d.tube/#!/v/mes/fplpcxr6"], ["YouTube (deleted)", "https://youtu.be/EIzjickYpEA"]] },
  { title: "#PizzaGate Part 3: Barack Obama's Close Ties to ACORN", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/DHMIRcUI-PizzaGate20Part203.jpeg", links: [["Notes", "https://peakd.com/pizzagate/@mes/video-notes-pizzagate-part-3-obama-s-close-ties-to-acorn"], ["BitChute", "https://www.bitchute.com/video/iYt5wd6idDyY/"], ["DTube", "https://d.tube/#!/v/mes/c8ez1kd4"], ["YouTube (deleted)", "https://youtu.be/pyYJ4OTVMgo"]] },
  { title: "#PizzaGate Part 2: ACORN Controversy", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/R41S5zZm-PizzaGate20Part202.jpeg", links: [["Notes", "https://peakd.com/pizzagate/@mes/video-notes-pizzagate-part-2-acorn-controversy"], ["BitChute", "https://www.bitchute.com/video/M2UnwOkUIckk"], ["DTube", "https://d.tube/#!/v/mes/1yn2oz65"], ["YouTube (deleted)", "https://youtu.be/PXO64aActSg"]] },
  { title: "#PizzaGate Part 1: Madeleine McCann Disappearance", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/3wsZnMBB-PizzaGate20Part201.jpeg", links: [["Notes", "https://peakd.com/pizzagate/@mes/video-notes-pizzagate-part-1-madeleine-mccann-disappearance"], ["BitChute", "https://www.bitchute.com/video/aYZB4RhUBIpR/"], ["DTube", "https://d.tube/#!/v/mes/vxdt0ze8"], ["YouTube (deleted)", "https://youtu.be/mdluzbv4MYA"]] },
    ],
  },
];

export const IMPORTANT_LINKS_HTML = `<h3>Links to Video Notes and Playlists</h3>
<ul>
<li><a href="https://peakd.com/pg/@mes/videos">Hive post: links and notes</a> &middot; <a href="https://mes.fm/pizzagate-drive">MES OneDrive files</a></li>
<li>Video playlists: <a href="https://mes.fm/links">MES Links</a> &middot; <a href="https://mes.fm/pg-bitchute">BitChute</a> &middot; <a href="https://odysee.com/$/playlist/d93456222ba64e13c31ec872f15a1e43da4d6bee">Odysee</a> &middot; <a href="https://mes.fm/pizzagate-playlist">YouTube</a> (deleted)</li>
</ul>
<h3>Links to YouTube Censorship</h3>
<ul>
<li><a href="https://peakd.com/hive-106474/@mes/have-to-delete-all-my-pizzagate-videos-to-prevent-youtube-from-deleting-my-account">YouTube Purge</a> &middot; <a href="https://peakd.com/dmania/@mes/youtube-believes-in-free-expression-unless-you-deny-fake-events-from-having-happened-1984-zg1hbmlh-7ath1">&ldquo;Event Denying&rdquo;</a></li>
<li>YouTube has a guideline made specifically for the Comet Ping Pong &ldquo;shooting&rdquo; psyop: <a href="https://support.google.com/youtube/answer/2802268?hl=en#zippy=%2Cother-types-of-content-that-violate-this-policy">Guidelines</a> (<a href="https://archive.vn/oWpLq">Archive</a>):
<blockquote><em>&ldquo;Targeting an individual and making claims they are involved in human trafficking in the context of a harmful conspiracy theory where the conspiracy is linked to direct threats or violent acts.&rdquo;</em></blockquote></li>
</ul>
<h3>More MES Video Series</h3>
<ul>
<li><a href="https://peakd.com/experiments/@mes/list">MES Experiments</a> &middot; <a href="https://mes.fm/experiments-draft">DRAFT Experiments</a> &middot; <a href="https://peakd.com/antigravity/@mes/series">Anti-Gravity</a> &middot; <a href="https://mes.fm/science-playlist">MES Science</a> &middot; <a href="https://mes.fm/freeenergy-playlist">Free Energy</a> &middot; <a href="https://peakd.com/truth/@mes/911">9/11 Truth</a> &middot; <a href="http://mes.fm/occult-playlist">Occult</a> &middot; <a href="https://peakd.com/pg/@mes/videos">PizzaGate</a> &middot; <a href="https://www.youtube.com/@mes/streams">MES Livestreams</a></li>
</ul>
`;
