// Content for mes.fm/antigravity ("MES Anti-Gravity") and its Series page mes.fm/antigravity-series. Hand-maintained; read by build.mjs.
//
// Converted (2026-10-08) from https://peakd.com/antigravity/@mes/series, newest first: the gyrocompass corrections video (Dec 2023), then Parts 6 down to 1.
// Add a new video at the TOP of the list. Item shape: { title, image, links: [[label, href], ...] }; the card goes to its first mes.fm link, else the Hive
// notes (peakd), else the first link. Part 6 is two videos, hence "BitChute 1" / "BitChute 2" ... The gyrocompass YouTube link comes from mes.fm/links.

export const SECTIONS = [
  {
    id: "antigravity-series",
    title: "Series",
    standalone: [
      { href: "/antigravity-playlist", title: "YouTube playlist", icon: "&#127916;" },
      { href: "/antigravity-bitchute", title: "BitChute playlist", icon: "&#127916;" },
      { href: "https://odysee.com/$/playlist/6e53d242296fd47f60c539a22612c4c237d76c23", title: "Odysee playlist", icon: "&#127916;" },
      { href: "https://peakd.com/antigravity/@mes/series", title: "Hive links and notes", icon: "&#128221;" },
    ],
    items: [
  { title: "How Gyrocompasses Work + Corrections to Earlier Videos", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/23xVgMwCVKwBMu9ddLcQCWD6tGbDqK6TzEAY3RYH1ssanQEvw8bKUsuH8i5Ug5zqM5Fi4.jpeg", links: [["Notes", "https://peakd.com/hive-128780/@mes/how-gyrocompasses-work"], ["3Speak", "https://3speak.tv/watch?v=mes/cbtlhxds"], ["Odysee", "https://odysee.com/@mes:8/How-Gyrocompasses-Work:a"], ["BitChute", "https://www.bitchute.com/video/p2VhJkjIbIEX/"], ["Rumble", "https://rumble.com/v441c10-how-gyrocompasses-work-corrections-to-earlier-videos.html"], ["YouTube", "https://youtu.be/JItGEGMwg90"]] },
  { title: "#AntiGravity Part 6: Objects in Rotation Defy 'Mainstream' Physics + MES Duality Concept", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/23uQvaS78hCNcSRSgDQrpoygJtyDq9j5QEnvVhEwdmdv5JCT67MzueTNMxgq6bks8siBS.jpeg", links: [["Notes", "https://peakd.com/antigravity/@mes/antigravity-part-6-video-1-objects-in-rotation-defy-mainstream-physics-mes-duality-concept"], ["PDF notes", "https://1drv.ms/b/s!As32ynv0LoaIh-xTV42m_NX2ZDQYIw"], ["Word notes", "https://1drv.ms/w/s!As32ynv0LoaIh75UFj1Vekcq1656wA"], ["Odysee", "https://odysee.com/@mes:8/-AntiGravity-Part-6-objects-in-rotation-defy-mainstream-physics:b"], ["BitChute 1", "https://www.bitchute.com/video/IS6BL47ytHEI/"], ["BitChute 2", "https://www.bitchute.com/video/sUnLAlGpiL3a/"], ["Rumble", "https://rumble.com/v20u0i0-antigravity-part-6-objects-in-rotation-defy-mainstream-physics-mes-duality-.html"], ["DTube 1", "https://d.tube/#!/v/mes/QmRy5XhziZB9aQfgyN2YCYJDusR6LbhMu1mi8zKbwXdW6J"], ["DTube 2", "https://d.tube/#!/v/mes/QmXf4iTM6dSSGBFZtnC7XtxbmWD8oWU1JMwgR5bcSU5pB7"], ["YouTube 1", "https://youtu.be/VLt1dSt_r18"], ["YouTube 2", "https://youtu.be/dKwwJe0znpA"]] },
  { title: "#AntiGravity Part 5: Spinning Wheels Balance UPSIDE DOWN! #Magic", image: "https://i.ytimg.com/vi/cj4CoFmYScc/maxresdefault.jpg", links: [["Notes", "https://peakd.com/antigravity/@mes/antigravity-part-5-spinning-wheels-balance-upside-down-magic"], ["3Speak", "https://3speak.tv/watch?v=mes/agoscupk"], ["Odysee", "https://odysee.com/@mes:8/antigravity-part-5-spinning-wheels:f"], ["BitChute", "https://www.bitchute.com/video/cj4CoFmYScc/"], ["Rumble", "https://rumble.com/v2885oc-antigravity-part-5-spinning-wheels-balance-upside-down.html"], ["DTube", "https://d.tube/#!/v/mes/b4s920um"], ["YouTube", "https://youtu.be/cj4CoFmYScc"]] },
  { title: "#AntiGravity Part 4: Spinning Wheels Precess with ZERO Angular Momentum or Centripetal Force!", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/23w2eJgWuAfVXKZ6YrN6aVJyMF6k6q5ft8yqVaks5NGdqjLQGekcseuXUTpeFnMwAMFeR.jpeg", links: [["Notes", "https://peakd.com/antigravity/@mes/antigravity-part-4-spinning-wheels-precess-with-no-angular-momentum-or-centripetal-force"], ["3Speak", "https://3speak.tv/watch?v=mes/oquchcof"], ["Odysee", "https://odysee.com/@mes:8/antigravity-part-4-spinning-wheels:0"], ["BitChute", "https://www.bitchute.com/video/oPLCMSK9Syw/"], ["Rumble", "https://rumble.com/v28879u-antigravity-part-4-spinning-wheels-precess-with-zero-angular-momentum-or-ce.html"], ["DTube", "https://d.tube/#!/v/mes/srqulau3"]] },
  { title: "#AntiGravity Part 3: Eric Laithwaite's Reality-Defying 1974 Lecture on Gyroscopes #HiddenScience", image: "https://images.hive.blog/640x0/https://files.peakd.com/file/peakd-hive/mes/23uQk8XpRRQfpF5JgGsBJvCVE9RnKqyTS3mR4g4qe4NwiHpbSJ1yPxwKJrWG9aMGsY6H5.jpeg", links: [["Notes", "https://peakd.com/antigravity/@mes/antigravity-part-3-eric-laithwaite-s-reality-defying-1974-lecture-on-gyroscopes-hiddenscience"], ["3Speak", "https://3speak.tv/watch?v=mes/diwbyxcu"], ["Odysee", "https://odysee.com/@mes:8/antigravity-part-3-eric-laithwaite-s:7"], ["BitChute", "https://www.bitchute.com/video/oPLCMSK9Syw/"], ["Rumble", "https://rumble.com/v288fhp-antigravity-part-3-eric-laithwaites-reality-defying-1974-lecture-on-gyrosc"], ["YouTube", "https://youtu.be/oPLCMSK9Syw/"]] },
  { title: "#AntiGravity Part 2: Eric Laithwaite Lifts a 40 lb Gyro Wheel Like a Feather!", image: "https://i.ytimg.com/vi/VUh6QXe4mMY/maxresdefault.jpg", links: [["Notes", "https://peakd.com/antigravity/@mes/antigravity-part-2-eric-laithwaite-lifts-a-40-lb-gyro-wheel-like-a-feather"], ["3Speak", "https://3speak.co/watch?v=mes/jmkxruom"], ["Odysee", "https://odysee.com/@mes:8/antigravity-part-2-eric-laithwaite-lifts:3"], ["BitChute", "https://www.bitchute.com/video/GJ7FsEEFPqJP/"], ["Rumble", "https://rumble.com/v288cxe-antigravity-part-2-eric-laithwaite-lifts-a-40-lb-gyro-wheel-like-a-feather.html"], ["DTube", "https://d.tube/#!/v/mes/s615aof1"], ["YouTube", "https://youtu.be/VUh6QXe4mMY"]] },
  { title: "#AntiGravity Part 1: Eric Laithwaite, Gyroscopes, & #HiddenScience + Saturn Symbolism + MORE", image: "https://i.ytimg.com/vi/cMLXHe2wKy8/maxresdefault.jpg", links: [["Notes", "https://peakd.com/antigravity/@mes/antigravity-part-1-eric-laithwaite-gyroscopes-and-hiddenscience-saturn-symbolism-notes-1-of-2"], ["3Speak", "https://3speak.tv/watch?v=mes/ygchzdxy"], ["Odysee", "https://odysee.com/@mes:8/AntiGravity-Part-1-Eric-Laithwaite-Gyroscopes:4"], ["BitChute", "https://www.bitchute.com/video/cMLXHe2wKy8/"], ["Rumble", "https://rumble.com/v288fuo-antigravity-part-1-eric-laithwaite-gyroscopes-and-hiddenscience-saturn-symb.html"], ["DTube", "https://d.tube/#!/v/mes/1nzi1p1u"], ["YouTube", "https://youtu.be/cMLXHe2wKy8"]] },
    ],
  },
];

export const IMPORTANT_LINKS_HTML = `<h3>Links to All Notes and Playlists</h3>
<ul>
<li><a href="https://peakd.com/antigravity/@mes/series">Hive post: links and notes</a> &middot; <a href="https://mes.fm/antigravity-onedrive">OneDrive all files</a></li>
<li>Playlists: <a href="https://mes.fm/antigravity-playlist">YouTube</a> &middot; <a href="https://mes.fm/antigravity-bitchute">BitChute</a> &middot; <a href="https://odysee.com/$/playlist/6e53d242296fd47f60c539a22612c4c237d76c23">Odysee</a></li>
<li><a href="https://peakd.com/antigravity/@mes/antigravity-part-6-video-1-objects-in-rotation-defy-mainstream-physics-mes-duality-concept">Objects in Rotation Defy Mainstream Physics + MES Duality</a> &middot; <a href="https://youtu.be/JItGEGMwg90">Correction to Gyrocompasses</a></li>
</ul>
<h3>More MES Series</h3>
<ul>
<li><a href="https://mes.fm/experiments">MES Experiments</a> &middot; <a href="https://mes.fm/experiments-draft">DRAFT Experiments</a> &middot; <a href="https://peakd.com/antigravity/@mes/series">Anti-Gravity</a> &middot; <a href="https://mes.fm/science">MES Science</a> &middot; <a href="https://mes.fm/freeenergy-playlist">Free Energy</a> &middot; <a href="https://peakd.com/truth/@mes/911">9/11 Truth</a> &middot; <a href="http://mes.fm/occult-playlist">Occult</a> &middot; <a href="https://mes.fm/pg">PizzaGate</a> &middot; <a href="https://mes.fm/livestreams">MES Livestreams</a> &middot; <a href="https://mes.fm/links">MES Links</a></li>
</ul>
`;
